In [34]:
try:
    import elasticsearch
    from elasticsearch import Elasticsearch
    
    import pandas as pd
    import json
    from ast import literal_eval
    from tqdm import tqdm
    import datetime
    import os
    import sys
    
    import os
    import tensorflow as tf
    import tensorflow_hub as hub
    import numpy as np
    
    from elasticsearch import helpers
    print("Loaded  .. . . . . . . .")
except Exception as E:
    print("Some Modules are Missing {} ".format(E))

Loaded  .. . . . . . . .

In [35]:
try:
 print("Loaded  s .. . . . . . . .")
 module_url = "/home/forsan/Downloads/universal-sentence-encoder_4" 
 model = hub.load(module_url)    
 print ("module %s loaded" % module_url)
except Exception as E:
    print("Some Modules are Missing {} ".format(E))

Loaded  s .. . . . . . . .
module /home/forsan/Downloads/universal-sentence-encoder_4 loaded

In [36]:
df = pd.read_csv("/home/forsan/Downloads/images (5).csv")

In [37]:
df.head(1)

     id                                              title
0  2361  A Saudi Arabian Gulf businessman sitting at a ...

In [38]:
def apply_transform(x):
    
    tem = str(x)
    x = tf.constant([tem])
    embeddings = model(x)
    x = np.asarray(embeddings)
    x = x[0].tolist()
    return x

In [42]:
try:
 print('start embdding ...')
 df["title_vector"] = df["title"].apply(apply_transform)
 print('end embdding ...')
except Exception as E:
    print("Some Modules are Missing {} ".format(E))

start embdding ...
end embdding ...

In [43]:
len(df["title_vector"].iloc[0])

512

In [44]:
df.head(1)

,id,title,ml_vector,title_vector
0,2361,A Saudi Arabian Gulf businessman sitting at a ...,"[-0.03021049126982689, 0.06228601932525635, -0...","[-0.03021049126982689, 0.06228601932525635, -0..."

In [45]:
Settings = {

   "mappings":{
       "properties":{
            "title": {
              "type": "text"
            },
            "title_vector": {
              "type": "dense_vector",
              "dims": 512
            }
    }
   }
}

In [46]:
ENDPOINT = "http://localhost:9200/"
es = Elasticsearch(timeout=600,hosts=ENDPOINT)

In [47]:
es.ping()

True

In [48]:
IndexName = 'arabstockimgdeven'
my = es.indices.create(index=IndexName, ignore=[400,404], body=Settings)

In [49]:
my

{'acknowledged': True,
 'shards_acknowledged': True,
 'index': 'arabstockimgdeven'}

In [50]:
df.columns

Index(['id', 'title', 'ml_vector', 'title_vector'], dtype='object')

In [53]:
def generator(df2):
    for c, line in enumerate(df2):
        yield {
    '_index': 'arabstockimgdeven',
   # '_type': '_doc',
    '_id': c+1,
    '_source': {
        "title":line.get("title", ""),
       'id':line.get('id', ""),
        'title_vector':line.get('title_vector', "")
    }
        }
    return 1

In [54]:
df22 = df.to_dict('records')
next(generator(df22))

{'_index': 'arabstockimgdeven',
 '_id': 1,
 '_source': {'title': 'A Saudi Arabian Gulf businessman sitting at a desk in front of a laptop, talking through a mobile phone, a Saudi company, an office job, a work environment',
  'id': 2361,
  'title_vector': [-0.03021049126982689,
   0.06228601932525635,
   -0.03524915128946304,
   0.02693304978311062,
   0.05703500658273697,
   -0.06953904777765274,
   0.042686671018600464,
   0.023693442344665527,
   0.06772022694349289,
   -0.04854009300470352,
   -0.011909657157957554,
   -0.014479989185929298,
   -0.019064899533987045,
   -0.014340095221996307,
   0.023884151130914688,
   -0.07175423204898834,
   -0.007888462394475937,
   0.03132487088441849,
   0.05627507343888283,
   -0.0004308786301407963,
   -0.0048030223697423935,
   -0.008519348688423634,
   0.06513410061597824,
   -0.04762867093086243,
   0.022342585027217865,
   -0.03370828181505203,
   -0.06193926930427551,
   0.0030579061713069677,
   0.005796200595796108,
   -0.06411945074796677,
   -0.020532626658678055,
   -0.02014206536114216,
   0.054590631276369095,
   0.06987768411636353,
   0.062150683254003525,
   -0.005610645283013582,
   -0.03590305894613266,
   -0.02640371024608612,
   -0.050591759383678436,
   -0.01527134608477354,
   0.06295181810855865,
   -0.0037730487529188395,
   0.005338604561984539,
   0.036287348717451096,
   0.06456585228443146,
   0.04824073985219002,
   -0.022101523354649544,
   -0.03937775269150734,
   0.008192646317183971,
   -0.040075283497571945,
   -0.035196613520383835,
   -0.017408955842256546,
   0.019201762974262238,
   0.06825871765613556,
   -0.024838736280798912,
   0.005455504637211561,
   0.009423479437828064,
   0.034042660146951675,
   -0.021693727001547813,
   -0.07093862444162369,
   0.046238284558057785,
   0.01712786592543125,
   -0.05569300428032875,
   0.022755825892090797,
   0.021375393494963646,
   -0.012874704785645008,
   -0.013208636082708836,
   -0.04762495309114456,
   0.009110833518207073,
   -0.037676602602005005,
   0.02058909833431244,
   0.05600392445921898,
   -0.057266607880592346,
   -0.05978138744831085,
   -0.058664847165346146,
   -0.07258536666631699,
   -0.019499877467751503,
   0.05387803539633751,
   0.03203051537275314,
   0.04461090639233589,
   0.06556108593940735,
   0.0643635094165802,
   0.005598238669335842,
   -0.05100731551647186,
   -0.06370647251605988,
   -0.04840358719229698,
   -0.057569246739149094,
   0.042896050959825516,
   -0.015021073631942272,
   -0.01625976525247097,
   0.01919517107307911,
   0.06603361666202545,
   0.04622095450758934,
   0.07034022361040115,
   -0.06997848302125931,
   -0.040324412286281586,
   0.05694897100329399,
   0.038697920739650726,
   0.06176600232720375,
   0.02576548606157303,
   0.05145777389407158,
   -0.016179637983441353,
   -0.05340796709060669,
   -0.037111591547727585,
   -0.07223106175661087,
   0.07031646370887756,
   -0.02471642568707466,
   0.011194584891200066,
   0.04790430888533592,
   -0.004534240812063217,
   0.048197101801633835,
   -0.03770441934466362,
   0.045196596533060074,
   -0.028608519583940506,
   -0.05382370948791504,
   -0.037651944905519485,
   -0.06287049502134323,
   0.06103641167283058,
   -0.06046048179268837,
   0.006678859703242779,
   -0.06560487300157547,
   -0.021606577560305595,
   -0.06543313711881638,
   -0.05486208200454712,
   0.035711389034986496,
   0.018571438267827034,
   0.0723235085606575,
   -0.06682482361793518,
   -0.026170281693339348,
   0.025388002395629883,
   -0.0699923112988472,
   -0.06355837732553482,
   0.0031446663197129965,
   -0.021383991464972496,
   -0.005337805952876806,
   0.017960358411073685,
   0.030182400718331337,
   0.012851144187152386,
   -0.03830661624670029,
   0.023799506947398186,
   -0.058627475053071976,
   0.05739353224635124,
   -0.01527099683880806,
   -0.023388221859931946,
   0.053715892136096954,
   -0.02832859382033348,
   0.03450877591967583,
   -0.05651397258043289,
   0.021090663969516754,
   0.006324539426714182,
   0.030962523072957993,
   0.02916955016553402,
   0.04025430232286453,
   0.03438496217131615,
   -0.06886449456214905,
   -0.06734531372785568,
   0.04439535364508629,
   0.050306547433137894,
   -0.06229032576084137,
   -0.03409219905734062,
   -0.05841488391160965,
   0.06629830598831177,
   -0.009964615106582642,
   -0.04763781279325485,
   0.04455476254224777,
   -0.02922593243420124,
   0.07056480646133423,
   0.059663254767656326,
   0.021379223093390465,
   -0.008066333830356598,
   0.05473105609416962,
   0.019403232261538506,
   -0.022670041769742966,
   -0.016991328448057175,
   -0.026257717981934547,
   -0.0319947674870491,
   0.06924977898597717,
   0.0606139674782753,
   -0.05921028554439545,
   -0.010140585713088512,
   0.033973805606365204,
   -0.02480255626142025,
   -0.04685886949300766,
   -0.06098359450697899,
   -0.05936592444777489,
   0.056977204978466034,
   -0.0719609335064888,
   -0.008484112098813057,
   0.032131534069776535,
   0.011722860857844353,
   0.04053524136543274,
   -0.01540776900947094,
   -0.05671354755759239,
   0.016239264979958534,
   -0.010560942813754082,
   0.04698793217539787,
   0.03275405615568161,
   -0.019559532403945923,
   -0.05580810457468033,
   0.03204001858830452,
   -0.07171357423067093,
   -0.061638131737709045,
   -0.040964897722005844,
   0.017636921256780624,
   -0.047309473156929016,
   -0.042880430817604065,
   -0.007821193896234035,
   -0.04400409013032913,
   0.07061845064163208,
   0.009467342868447304,
   0.02084471471607685,
   0.07213898748159409,
   0.054260239005088806,
   0.0278822910040617,
   -0.020962640643119812,
   -0.0011816247133538127,
   0.00415113614872098,
   0.06701590865850449,
   -0.07178134471178055,
   -0.050393909215927124,
   0.05354342237114906,
   0.008130974136292934,
   0.02611668035387993,
   0.044197212904691696,
   -0.023081930354237556,
   0.007153182756155729,
   0.03127731382846832,
   -0.06246334686875343,
   0.07061102241277695,
   0.03849177807569504,
   -0.05300223454833031,
   0.005110092926770449,
   -0.027121400460600853,
   -0.04533164203166962,
   0.06074066832661629,
   -0.07058627903461456,
   -0.05249778926372528,
   -0.04207444563508034,
   0.011318013072013855,
   0.05324273183941841,
   0.024699078872799873,
   0.029053719714283943,
   -0.05347210913896561,
   -0.04542019963264465,
   -0.060649480670690536,
   0.03941905498504639,
   -0.0498683899641037,
   -0.04357919096946716,
   0.027368884533643723,
   -0.048101939260959625,
   -0.058492906391620636,
   0.04841417074203491,
   -0.02016533352434635,
   0.02771935611963272,
   -0.013106214813888073,
   0.04873814806342125,
   0.046546462923288345,
   0.013984729535877705,
   -0.015815958380699158,
   0.06790977716445923,
   0.017261162400245667,
   0.07040626555681229,
   -0.051006902009248734,
   0.032766781747341156,
   0.052440911531448364,
   -0.05872194096446037,
   0.03453690558671951,
   -0.03315259516239166,
   -0.016779949888586998,
   0.05922563746571541,
   -0.04297745227813721,
   0.0020626008044928312,
   0.013819362968206406,
   0.06278543919324875,
   0.06801541149616241,
   0.061162929981946945,
   -0.05712806060910225,
   0.013559057377278805,
   0.010673748329281807,
   -0.032714150846004486,
   -0.0562841072678566,
   -0.015136237256228924,
   0.06293674558401108,
   -0.06058921292424202,
   0.056848153471946716,
   0.024375036358833313,
   0.024929100647568703,
   -0.054398175328969955,
   -0.0164028313010931,
   -0.04046078771352768,
   -0.04645897448062897,
   -0.03623274341225624,
   0.06567445397377014,
   0.06774618476629257,
   -0.03704528138041496,
   -0.06173102185130119,
   0.054175928235054016,
   -0.0567953921854496,
   -0.07080014795064926,
   0.018012531101703644,
   -0.018494680523872375,
   -0.06792694330215454,
   -0.006792036816477776,
   -3.405556344659999e-05,
   -0.06482993066310883,
   -0.03886895626783371,
   0.054712925106287,
   0.048787374049425125,
   -0.041882503777742386,
   -0.05366357043385506,
   -0.01237498875707388,
   -0.07041125744581223,
   -0.030802501365542412,
   0.07056116312742233,
   0.05462675169110298,
   0.010970661416649818,
   0.02552497759461403,
   -0.01341643650084734,
   -0.04291866347193718,
   -0.029986392706632614,
   -0.032363761216402054,
   0.027650758624076843,
   -0.04581752419471741,
   -0.04013897851109505,
   -0.06634236872196198,
   -0.010341438464820385,
   -0.05461571738123894,
   -0.0651855617761612,
   0.06022609770298004,
   0.030780620872974396,
   0.0012107973452657461,
   -0.035581544041633606,
   0.034465186297893524,
   0.01934782788157463,
   -0.005238309968262911,
   -0.06575322896242142,
   -0.020868228748440742,
   0.02586965449154377,
   0.06593167036771774,
   -0.023514466360211372,
   -0.024386731907725334,
   -0.02216547727584839,
   0.055930741131305695,
   -0.05761736258864403,
   0.011206437833607197,
   -0.03697963058948517,
   0.04336703568696976,
   0.031207043677568436,
   0.022366316989064217,
   -0.04177192971110344,
   -0.053887415677309036,
   -0.044329944998025894,
   -0.03948598355054855,
   -0.06956769526004791,
   -0.07021962106227875,
   -0.07261854410171509,
   -0.07055016607046127,
   -0.061748385429382324,
   0.004899203777313232,
   -0.010414812713861465,
   0.04643826559185982,
   0.01684078760445118,
   0.031599465757608414,
   0.04137754067778587,
   0.00978363212198019,
   0.05548970401287079,
   0.0556844063103199,
   -0.030181441456079483,
   0.04923340305685997,
   -0.018251197412610054,
   0.06591344624757767,
   0.06575003266334534,
   0.004792464897036552,
   0.03290330991148949,
   -0.038022421300411224,
   -0.044550009071826935,
   0.0506778210401535,
   0.012381953187286854,
   0.03578413650393486,
   0.044103458523750305,
   0.07046019285917282,
   0.041688740253448486,
   0.025687050074338913,
   0.05520184338092804,
   -0.008059000596404076,
   -0.07093123346567154,
   -0.04883949086070061,
   -0.06681894510984421,
   0.03250536695122719,
   0.03233173489570618,
   -0.05210205167531967,
   0.002253845799714327,
   -0.06035136803984642,
   0.03299285098910332,
   0.0371490903198719,
   0.032992035150527954,
   -0.0438956655561924,
   -0.05648539587855339,
   0.054082296788692474,
   0.03596915677189827,
   0.018162325024604797,
   -0.0032754314597696066,
   -0.04826921224594116,
   -0.001906189019791782,
   0.04410035163164139,
   0.011949863284826279,
   -0.0710756853222847,
   -0.05242422968149185,
   -0.002338444348424673,
   -0.006559782195836306,
   0.03795705735683441,
   -0.061258845031261444,
   0.01655678078532219,
   -0.033905159682035446,
   -0.0063645015470683575,
   -0.02792089805006981,
   0.07152776420116425,
   0.000685832928866148,
   -0.06862989813089371,
   0.04830747842788696,
   -0.012338485568761826,
   0.061149485409259796,
   0.023276738822460175,
   0.018253268674016,
   -0.015000519342720509,
   0.06470130383968353,
   -0.032837431877851486,
   -0.04241396486759186,
   0.003236495889723301,
   0.07050744444131851,
   0.031906843185424805,
   0.046178530901670456,
   -0.07110295444726944,
   0.031749822199344635,
   0.018141701817512512,
   0.06712128221988678,
   -0.032550349831581116,
   0.05423931032419205,
   0.0695020854473114,
   0.012721746228635311,
   -0.044852741062641144,
   -0.04001159593462944,
   0.060829490423202515,
   -0.06003934517502785,
   -0.06190565228462219,
   -0.011645653285086155,
   0.051634229719638824,
   -0.03802875429391861,
   0.05201219767332077,
   0.0604865700006485,
   0.07202067971229553,
   -0.029883839190006256,
   -0.021145615726709366,
   -0.01268843375146389,
   -0.03321109339594841,
   -0.01256274338811636,
   0.04540887847542763,
   -0.04516257345676422,
   -0.004150832537561655,
   -0.0695437341928482,
   0.06285084038972855,
   0.009008357301354408,
   0.06051076203584671,
   -0.039650216698646545,
   -0.011253086850047112,
   0.05149175226688385,
   -0.014286985620856285,
   -0.062031082808971405,
   0.044742047786712646,
   0.037086714059114456,
   0.011748837307095528,
   0.02930055931210518,
   0.06334621459245682,
   -0.058696724474430084,
   0.033324312418699265,
   0.0530163012444973,
   -0.029848065227270126,
   -0.07136596739292145,
   -0.0400288850069046,
   -0.06397032737731934,
   -0.03357669338583946,
   -0.019942861050367355,
   0.035806503146886826,
   -0.020622238516807556,
   0.07125633955001831,
   -0.00018516156706027687,
   -0.019492315128445625,
   0.04861556738615036,
   0.06210501864552498,
   0.03161253407597542,
   0.04390345513820648,
   -0.03784225881099701,
   -0.06750994920730591,
   -0.042692895978689194,
   -0.016570402309298515,
   0.05036350339651108,
   0.01545190904289484,
   -0.07027174532413483,
   -0.057473551481962204,
   0.05511264503002167,
   -0.023910533636808395,
   0.039324063807725906,
   -0.04921938106417656,
   0.04577517881989479,
   0.0019479884067550302,
   0.0009482078603468835,
   -0.009632152505218983,
   -0.038404397666454315,
   0.003960559610277414,
   -0.04913816601037979,
   -0.06050596758723259,
   -0.06490618735551834]}}

In [55]:
try:
    print("start working")
    res = helpers.bulk(es, generator(df22))
    print("end Working")
except Exception as E:
    print("Some Modules are Missing {} ".format(E))

start working
end Working

In [60]:
title = "Krish Trish and Baltiboy: Best Friends Forever"
INPUT = input("Enter input query")

x = apply_transform(INPUT)
Query = {
   "_source":[
      "title","id"
   ],
   "size":3000,
   "query":{
      "script_score":{
         "query":{
           # "match":{"title":INPUT}
             "match_all": {}
         },
         "script":{
            "source":"cosineSimilarity(params.query_vector, 'title_vector') + 1.0",
       #  "source": """
        #  double value = dotProduct(params.query_vector, 'ml_vector');
         # return sigmoid(1, Math.E, -value); 
        #""",
                     #"source": "1 / (1 + l1norm(params.query_vector, 'ml_vector'))", 

            "params":{
               "query_vector":x

            }
         }
      }
   }
}


resp = es.search(index="arabstockimgdeven",  body=Query)

print("Got %d Hits:" % resp['hits']['total']['value'])
#print(resp)
for hit in resp['hits']['hits']:
    print(  hit["_source"])

Enter input query horse

Got 10000 Hits:
{'id': 35591, 'title': 'Close-up of a black thoroughbred Arabian horse, horse breeding and training, thoroughbred Arabian horse, horse stable, horse farm'}
{'id': 17694, 'title': 'Close-up of a purebred Arabian horse, dressage, horse training, purebred Arabian horse, horse riding, equestrian'}
{'id': 17734, 'title': 'Close-up of a purebred Arabian horse, dressage, horse training, purebred Arabian horse, horse riding, equestrian'}
{'id': 35595, 'title': 'Close-up of a purebred white Arabian horse, horse breeding and training, thoroughbred Arabian horse, horse stable, horse farm'}
{'id': 44661, 'title': 'Close-up of a purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, thoroughbred Arabian horses, horse stables, horse farm'}
{'id': 44662, 'title': 'Close-up of a purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, thoroughbred Arabian horses, horse stables, horse farm'}
{'id': 35592, 'title': 'Close-up of the face of a purebred Arabian horse in brown, breeding and training horses, thoroughbred Arabian horses, horse stables, horse farm'}
{'id': 36190, 'title': 'Thoroughbred Arabian horses on a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36191, 'title': 'Thoroughbred Arabian horses on a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36192, 'title': 'Thoroughbred Arabian horses on a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36193, 'title': 'Thoroughbred Arabian horses on a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36003, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36004, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36005, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36006, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36007, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36008, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36009, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36010, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36085, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36086, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36087, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36091, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36092, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36093, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36094, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36095, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36096, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 36097, 'title': 'Thoroughbred Arabian horses in a horse farm, breeding and training horses in Saudi Arabia, purebred Arabian horses, horse stables, horse farm'}
{'id': 35494, 'title': 'White purebred Arabian horse, beautiful Arabian horse, hobby horse riding, horse stable, horse barn, pet breeding'}
{'id': 35503, 'title': 'White purebred Arabian horse, beautiful Arabian horse, hobby horse riding, horse stable, horse barn, pet breeding'}
{'id': 35902, 'title': 'A picture of a purebred brown Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27062, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27063, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27064, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27065, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27066, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27067, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27068, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27093, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27094, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27095, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27096, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27097, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27621, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27622, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27623, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27624, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27625, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27626, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27627, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27628, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27629, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27630, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27649, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 27650, 'title': 'Close-up of a purebred white Arabian horse, beautiful Arabian horse, breeding and training of horses, thoroughbred Arabian horses, horse stable, horse farm'}
{'id': 35589, 'title': 'A picture of a purebred black Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35590, 'title': 'A picture of a purebred black Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35644, 'title': 'A picture of a purebred black Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35600, 'title': 'A picture of a purebred white Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35601, 'title': 'A picture of a purebred white Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35602, 'title': 'A picture of a purebred white Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35603, 'title': 'A picture of a purebred white Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35640, 'title': 'A picture of a purebred white Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35641, 'title': 'A picture of a purebred white Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35642, 'title': 'A picture of a purebred white Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35643, 'title': 'A picture of a purebred white Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35903, 'title': 'A picture of a purebred white Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35904, 'title': 'A picture of a purebred white Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35905, 'title': 'A picture of a purebred white Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 35608, 'title': 'A picture of a purebred Arabian horse in brown, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27034, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27036, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27037, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27038, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27039, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27040, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27041, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27042, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27043, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27044, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27046, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27047, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27048, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27049, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27050, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27051, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27052, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27053, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27054, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27055, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27056, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27057, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27058, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27059, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27060, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27061, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27070, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27071, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27072, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27073, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27074, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27075, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27076, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27077, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27078, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27079, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27080, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27081, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27082, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27083, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27631, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27632, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27633, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27634, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}
{'id': 27635, 'title': 'A picture of a white purebred Arabian horse, a beautiful Arabian horse, breeding and training horses, purebred Arabian horses, horse stables, horse farm'}