In [1]:
try:
    import elasticsearch
    from elasticsearch import Elasticsearch
    
    import pandas as pd
    import json
    from ast import literal_eval
    from tqdm import tqdm
    import datetime
    import os
    import sys
    
    import os
    import tensorflow as tf
    import tensorflow_hub as hub
    import numpy as np
    
    from elasticsearch import helpers
    print("Loaded  .. . . . . . . .")
except Exception as E:
    print("Some Modules are Missing {} ".format(E))

2022-05-25 23:08:11.044948: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-25 23:08:11.045012: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

Loaded  .. . . . . . . .

In [2]:
module_url = "https://tfhub.dev/google/universal-sentence-encoder/4" 
model = hub.load(module_url)    
print ("module %s loaded" % module_url)

2022-05-25 23:08:22.981647: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-05-25 23:08:22.981673: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-05-25 23:08:22.981694: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (devibrahim-forsan): /proc/driver/nvidia/version does not exist
2022-05-25 23:08:22.981952: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-25 23:08:24.075787: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 34133760 exceeds 10% of free system memory.
2022-05-25 23:08:24.280756: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 34133760 exceeds 10% of free system memory.
2022-05-25 23:08:24.392224: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 34133760 exceeds 10% of free system memory.
2022-05-25 23:08:24.498358: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 34133760 exceeds 10% of free system memory.
2022-05-25 23:08:24.596141: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 34133760 exceeds 10% of free system memory.

module https://tfhub.dev/google/universal-sentence-encoder/4 loaded

In [5]:
df = pd.read_csv("/home/forsan/Downloads/images (3).csv")

In [29]:
df.head(1)

  title    id
0   eee  2357

In [6]:
def apply_transform(x):
    
    tem = str(x)
    x = tf.constant([tem])
    embeddings = model(x)
    x = np.asarray(embeddings)
    x = x[0].tolist()
    return x

In [7]:
df["ml_vector"] = df["title"].apply(apply_transform)

In [8]:
len(df["ml_vector"].iloc[0])

512

In [10]:
df.head(1)

,id,title,ml_vector
0,26901,اجتماع زملاء عمل عربيون سعوديون خليجيون في...,"[-0.0581899955868721, 0.004004060756415129, 0...."

In [42]:
Settings = {
   "settings":{
      "number_of_shards":1,
      "number_of_replicas":0,
        "analysis": {
      "filter": {
        "arabic_stop": {
          "type":       "stop",
          "stopwords":  "_arabic_" 
        },
        "arabic_keywords": {
          "type":       "keyword_marker",
          "keywords":   ["مثال"] 
        },
        "arabic_stemmer": {
          "type":       "stemmer",
          "language":   "arabic"
        }
      },
      "analyzer": {
        "rebuilt_arabic": {
          "tokenizer":  "standard",
          "filter": [
            "lowercase",
            "decimal_digit",
            "arabic_stop",
            "arabic_normalization",
            "arabic_keywords",
            "arabic_stemmer"
          ]
        }
      }
    }
   },
   "mappings":{
       "properties":{
          "ml_vector":{
         "type":"dense_vector",
         "dims":512
      } 
    }
   }
}

In [9]:
ENDPOINT = "http://localhost:9200/"
es = Elasticsearch(timeout=600,hosts=ENDPOINT)

In [10]:
es.ping()

True

In [44]:
IndexName = 'arabstockimgdevv9'
my = es.indices.create(index=IndexName, ignore=[400,404], body=Settings)

In [45]:
my

{'acknowledged': True,
 'shards_acknowledged': True,
 'index': 'arabstockimgdevv9'}

In [46]:
df.columns

Index(['title', 'id', 'ml_vector'], dtype='object')

In [52]:
def generator(df2):
    for c, line in enumerate(df2):
        yield {
    '_index': 'arabstockimgdevv9',
   # '_type': '_doc',
    '_id': c+1,
    '_source': {
        "title":line.get("title", ""),
       'id':line.get('id', ""),
        'ml_vector':line.get('ml_vector', "")
    }
        }
    return 1

In [53]:
df22 = df.to_dict('records')
next(generator(df22))

{'_index': 'arabstockimgdevv9',
 '_id': 1,
 '_source': {'title': 'eee',
  'id': 2357,
  'ml_vector': [-0.054026804864406586,
   -0.03842293843626976,
   0.05653785169124603,
   0.06373250484466553,
   -0.019726933911442757,
   0.023887624964118004,
   0.0139841940253973,
   -0.07408511638641357,
   0.05501914024353027,
   -0.03269156813621521,
   -0.0397510901093483,
   0.04740298539400101,
   -0.020027706399559975,
   -0.044217370450496674,
   -0.07171943038702011,
   0.013836477883160114,
   0.015241413377225399,
   0.051613256335258484,
   0.05137060955166817,
   -0.02418549358844757,
   0.07176473736763,
   -0.022440357133746147,
   0.04952561855316162,
   -0.05686269327998161,
   -0.05336103215813637,
   0.05125395581126213,
   0.013357373885810375,
   -0.03176634758710861,
   -0.03422686085104942,
   -0.0017391917062923312,
   0.006891636177897453,
   -0.04215896874666214,
   -0.03958765044808388,
   -0.06786327809095383,
   0.0647006705403328,
   -0.06879260390996933,
   0.017542773857712746,
   0.08008121699094772,
   -0.018433859571814537,
   0.07960997521877289,
   0.04008840397000313,
   0.021168110892176628,
   -0.02916675992310047,
   -0.018548499792814255,
   0.03313477709889412,
   0.07439318299293518,
   0.03841232508420944,
   -0.02452743798494339,
   -0.04223654419183731,
   -0.06752186268568039,
   -0.07239193469285965,
   0.00249694986268878,
   0.07717753201723099,
   0.08789671957492828,
   0.035171572118997574,
   0.039613813161849976,
   -0.060122519731521606,
   0.026996329426765442,
   -0.0046868715435266495,
   0.04847615212202072,
   0.0020807767286896706,
   -0.013545614667236805,
   -7.072742300806567e-05,
   -0.057219211012125015,
   0.0760435089468956,
   0.029097696766257286,
   -0.022955479100346565,
   -0.0560121089220047,
   0.017127886414527893,
   0.06395307928323746,
   -0.036279890686273575,
   -0.02791077084839344,
   -0.07202531397342682,
   -0.0033359848894178867,
   -0.01646076887845993,
   -0.027999108657240868,
   0.0260879248380661,
   -0.05383412912487984,
   0.050576504319906235,
   -0.0381922610104084,
   -0.07073591649532318,
   -0.002861237619072199,
   -0.02905222214758396,
   0.017174558714032173,
   -0.03634742274880409,
   -0.007298251613974571,
   -0.0198933444917202,
   0.0557512529194355,
   0.0647185668349266,
   -0.0046313791535794735,
   -0.04602079838514328,
   0.044991444796323776,
   -0.008591994643211365,
   -0.07891335338354111,
   0.017995361238718033,
   0.05151590332388878,
   -0.026736397296190262,
   -0.07541270554065704,
   0.01241181418299675,
   -0.026898983865976334,
   0.010438666678965092,
   -0.058454081416130066,
   0.039075855165719986,
   0.04537675529718399,
   -0.005325804930180311,
   0.0038964087143540382,
   0.03783688321709633,
   0.012037855572998524,
   0.010348564945161343,
   -0.004822195507586002,
   0.021121278405189514,
   0.05233967304229736,
   -0.00463867699727416,
   0.030790038406848907,
   -0.027452312409877777,
   0.0369381420314312,
   -0.07707931846380234,
   -0.027518300339579582,
   0.031100580468773842,
   0.0404314324259758,
   -0.03085866943001747,
   -0.0029934276826679707,
   0.03720377758145332,
   -0.03265223652124405,
   0.08159813284873962,
   -0.048550475388765335,
   0.032996825873851776,
   -0.045631296932697296,
   0.022399259731173515,
   0.04953137785196304,
   -0.05257581174373627,
   0.044086799025535583,
   0.07759027928113937,
   0.07253585010766983,
   -0.021471448242664337,
   0.047906242311000824,
   0.03293408080935478,
   -0.041423168033361435,
   -0.007774025667458773,
   -0.016880767419934273,
   -0.07266627997159958,
   0.06119257211685181,
   0.02212901972234249,
   -0.034699175506830215,
   0.02980554848909378,
   0.0427468940615654,
   -0.013036785647273064,
   -0.05372917652130127,
   -0.02050808258354664,
   -0.018166767433285713,
   -0.011292205192148685,
   0.043359480798244476,
   -0.04097240790724754,
   0.07114560157060623,
   0.023359868675470352,
   -0.04104186221957207,
   -0.07401487231254578,
   0.0641595795750618,
   -0.033707063645124435,
   0.03185073658823967,
   0.043855104595422745,
   0.038897864520549774,
   -0.047384925186634064,
   -0.0762220174074173,
   0.015762021765112877,
   -0.01763232983648777,
   -0.031099533662199974,
   -0.0024090714287012815,
   0.07171296328306198,
   0.013086609542369843,
   -0.0623655803501606,
   0.05480651929974556,
   -0.01694446988403797,
   -0.07148145139217377,
   -0.05449686944484711,
   -0.009837326593697071,
   0.012869438156485558,
   -0.033938564360141754,
   -0.05725403130054474,
   0.0010998060461133718,
   0.006051083095371723,
   -0.027101967483758926,
   -0.06765950471162796,
   0.05018173158168793,
   0.026910806074738503,
   0.02893874980509281,
   -0.023664815351366997,
   -0.024287616834044456,
   0.07301468402147293,
   0.03614719957113266,
   0.020431824028491974,
   -0.03630508854985237,
   -0.024893397465348244,
   -0.06365212798118591,
   0.016207540407776833,
   -0.05902741476893425,
   -0.03086807020008564,
   -0.031746458262205124,
   0.026782091706991196,
   0.03348023444414139,
   -0.08509109914302826,
   -0.012302697636187077,
   -0.06298337131738663,
   0.01994611695408821,
   -0.05386481061577797,
   -0.017049124464392662,
   -0.04336509108543396,
   0.006296973675489426,
   0.05712878331542015,
   -0.056800056248903275,
   0.023886574432253838,
   0.019046567380428314,
   -0.00815212819725275,
   0.043593864887952805,
   0.05125082656741142,
   0.028711538761854172,
   -0.0647699311375618,
   -0.0670304223895073,
   -0.039194513112306595,
   -0.00928530003875494,
   -0.0029774836730211973,
   0.05289964750409126,
   -4.4070406147511676e-05,
   -0.05722362920641899,
   0.024745609611272812,
   0.009629249572753906,
   -0.035687968134880066,
   -0.06032102182507515,
   -0.05101833492517471,
   0.00027408264577388763,
   -0.00798797607421875,
   -0.04204854741692543,
   0.005006041843444109,
   0.09280896186828613,
   -0.0634448304772377,
   0.039449889212846756,
   -0.012303613126277924,
   -0.010347790084779263,
   -0.06113828718662262,
   -0.02869090624153614,
   0.001756561454385519,
   0.030870066955685616,
   -0.031295325607061386,
   -0.04490034282207489,
   0.07095840573310852,
   -0.05497462674975395,
   0.05314713716506958,
   -0.06489522010087967,
   -0.05480562150478363,
   -0.016987387090921402,
   0.00029391745920293033,
   0.07885490357875824,
   0.038509584963321686,
   -0.00291848205961287,
   0.06294776499271393,
   -0.07508143037557602,
   0.005699506960809231,
   0.07145220786333084,
   -0.025401055812835693,
   0.04322182759642601,
   -0.01482111494988203,
   -0.007531450595706701,
   -0.07315760850906372,
   -0.07662494480609894,
   0.06718848645687103,
   -0.06813047081232071,
   0.07151634246110916,
   -0.04537639021873474,
   -0.023167502135038376,
   -0.07043861597776413,
   -0.007854358293116093,
   0.05878143012523651,
   -0.019117292016744614,
   -0.030532918870449066,
   0.08183784037828445,
   0.008987991139292717,
   -0.022143661975860596,
   0.04468868300318718,
   0.06950012594461441,
   -0.07702118903398514,
   0.004017560742795467,
   0.001683128415606916,
   0.026018600910902023,
   0.056594789028167725,
   -0.033128462731838226,
   -0.03245789557695389,
   0.05076673999428749,
   -0.05111585557460785,
   -0.03634817153215408,
   -0.07027581334114075,
   0.01927630789577961,
   -0.06587786972522736,
   0.024584902450442314,
   0.009670248255133629,
   0.0319359116256237,
   0.016394995152950287,
   -0.06957772374153137,
   -0.06615837663412094,
   0.02533261477947235,
   0.04564288631081581,
   -0.04202454164624214,
   -0.008671539835631847,
   -0.058302849531173706,
   0.061289988458156586,
   -0.014807903207838535,
   0.05831708759069443,
   -0.00441606855019927,
   0.011534699238836765,
   -0.01562974601984024,
   -0.04851726070046425,
   -0.032442573457956314,
   -0.05483778193593025,
   -0.054869845509529114,
   0.00543850427493453,
   -0.008797825314104557,
   0.027362190186977386,
   0.022154197096824646,
   -0.08170939236879349,
   -0.05253468453884125,
   -0.0264821108430624,
   0.05490337312221527,
   -0.0446716733276844,
   -0.046390678733587265,
   0.0007723502931185067,
   0.012842472642660141,
   0.030434006825089455,
   -0.03959183022379875,
   0.047332193702459335,
   0.00878096278756857,
   -0.01702781207859516,
   0.003279147669672966,
   0.03289509192109108,
   -0.08092931658029556,
   0.08517318218946457,
   -0.05719686672091484,
   0.015502522699534893,
   0.038600463420152664,
   0.04839671030640602,
   -0.0522783137857914,
   -0.004124182742089033,
   -0.04680626839399338,
   0.02660609968006611,
   -0.009275970049202442,
   0.025171635672450066,
   -0.06425944715738297,
   0.030174674466252327,
   -0.052521612495183945,
   -0.04598260298371315,
   -0.020024960860610008,
   0.0030139293521642685,
   -0.030382083728909492,
   0.0647590383887291,
   0.0186269860714674,
   0.015919407829642296,
   -0.004515585955232382,
   -0.05003504827618599,
   -0.07487504929304123,
   -0.06678944826126099,
   0.044498808681964874,
   -0.03819818049669266,
   0.013419657945632935,
   -0.04745473712682724,
   0.08173839002847672,
   -0.009946937672793865,
   -0.0012816464295610785,
   -0.025147028267383575,
   0.025439638644456863,
   0.02134418860077858,
   0.002670725341886282,
   -0.03415411338210106,
   0.05064677819609642,
   -0.06497879326343536,
   0.055173590779304504,
   -0.03189297392964363,
   -0.07142139226198196,
   -0.038774099200963974,
   0.00826418586075306,
   -0.07121051847934723,
   0.053957514464855194,
   -0.08189989626407623,
   0.05661539360880852,
   0.02348477952182293,
   0.00877548661082983,
   -0.0863959789276123,
   0.02291034162044525,
   -0.0743182972073555,
   0.048674605786800385,
   0.07384605705738068,
   0.009323532693088055,
   -0.0024044145829975605,
   -0.03377895802259445,
   0.0807652696967125,
   0.03184789419174194,
   -0.0648421123623848,
   0.01899362914264202,
   -0.05387967452406883,
   0.06660978496074677,
   0.07601357251405716,
   -0.04257117584347725,
   0.03989449888467789,
   -0.007103349082171917,
   0.0846031904220581,
   -0.002690668450668454,
   -0.04039234295487404,
   0.024026157334446907,
   0.06163632124662399,
   0.005294770933687687,
   0.028352322056889534,
   0.04850449785590172,
   0.018773535266518593,
   -0.03563912212848663,
   0.019524209201335907,
   -0.00324318278580904,
   -0.006166640669107437,
   -0.04039410874247551,
   -0.016155531629920006,
   0.08515487611293793,
   -0.022918477654457092,
   -0.04006616026163101,
   0.018347255885601044,
   0.038913216441869736,
   -0.08571115881204605,
   -0.07610020786523819,
   0.049202874302864075,
   -0.0367656871676445,
   0.00997812021523714,
   -0.023148201406002045,
   0.06914713978767395,
   -0.02119734324514866,
   0.002380089834332466,
   -0.06416164338588715,
   -0.032258033752441406,
   -0.0663779228925705,
   -0.0054730759002268314,
   0.04704497009515762,
   0.018103376030921936,
   0.017061127349734306,
   0.023823987692594528,
   -0.03469330072402954,
   0.09124425053596497,
   -0.028894705697894096,
   -0.03178009018301964,
   0.03751637786626816,
   0.014502482488751411,
   -0.012555086053907871,
   -0.03580435737967491,
   -0.028960492461919785,
   -0.01184273324906826,
   0.03236617520451546,
   -0.0056631979532539845,
   -0.013330665417015553,
   0.0014721155166625977,
   -0.004504592157900333,
   0.023846538737416267,
   0.01062270812690258,
   -0.0632147267460823,
   0.023128865286707878,
   -0.05493997409939766,
   0.06008950620889664,
   -0.05310953035950661,
   0.033158473670482635,
   0.04780306667089462,
   -0.03088604472577572,
   0.015473872423171997,
   0.02529398910701275,
   0.04042034596204758,
   0.02644786424934864,
   0.02676970511674881,
   0.03773660585284233,
   0.013239598833024502,
   0.04115109518170357,
   -0.019614320248365402,
   0.06704370677471161,
   0.027535468339920044,
   0.06943093240261078,
   0.01315488200634718,
   -0.03593273460865021,
   -0.001558505347929895,
   0.03207311034202576,
   0.05499354377388954,
   -0.04634809121489525,
   -0.07598365843296051,
   0.022489087656140327,
   0.044371746480464935,
   0.022701499983668327,
   0.03054976649582386,
   -0.04657731205224991,
   0.057284995913505554,
   0.028862271457910538,
   -0.05218137055635452,
   -0.005445985589176416,
   0.04078710451722145,
   -0.034451600164175034,
   -0.0414041168987751,
   -0.006355587858706713,
   -0.029329048469662666,
   0.06967300176620483,
   -0.008471831679344177,
   0.06362753361463547,
   0.02366829290986061,
   0.023035723716020584,
   0.008498583920300007,
   -0.03185214847326279,
   -0.08955687284469604,
   0.05944940820336342,
   0.05914272367954254,
   -0.01708265393972397,
   -0.07670924812555313,
   0.05971861630678177,
   -0.051417719572782516,
   0.007355287671089172,
   -0.07041109353303909]}}

In [54]:
try:
    print("start working")
    res = helpers.bulk(es, generator(df22))
    print("end Working")
except Exception as E:
    print("Some Modules are Missing {} ".format(E))

start working
end Working

In [21]:
title = "Krish Trish and Baltiboy: Best Friends Forever"
INPUT = input("Enter input query")

x = apply_transform(INPUT)
Query = {
   "_source":[
      "title","id"
   ],
   "size":3000,
   "query":{
      "script_score":{
         "query":{
           # "match":{"title":INPUT}
             "match_all": {}
         },
         "script":{
            "source":"cosineSimilarity(params.query_vector, 'ml_vector') + 1.0",
       #  "source": """
        #  double value = dotProduct(params.query_vector, 'ml_vector');
         # return sigmoid(1, Math.E, -value); 
        #""",
                     #"source": "1 / (1 + l1norm(params.query_vector, 'ml_vector'))", 

            "params":{
               "query_vector":x

            }
         }
      }
   }
}


resp = es.search(index="arabstockimgdevv9",  body=Query)

print("Got %d Hits:" % resp['hits']['total']['value'])
#print(resp)
for hit in resp['hits']['hits']:
    print(  hit["_source"])

Enter input query طبيب

Got 10000 Hits:
{'id': 34851, 'title': '1639994790AdgpSLH5mm'}
{'id': 28623, 'title': 'مكرر'}
{'id': 25401, 'title': '16305772657THP7r3m2S'}
{'id': 25694, 'title': 'الاوان '}
{'id': 47136, 'title': 'حذذف'}
{'id': 47140, 'title': 'حذذف'}
{'id': 47143, 'title': 'حذذف'}
{'id': 47149, 'title': 'حذذف'}
{'id': 47153, 'title': 'حذذف'}
{'id': 47154, 'title': 'حذذف'}
{'id': 47155, 'title': 'حذذف'}
{'id': 47163, 'title': 'حذذف'}
{'id': 47164, 'title': 'حذذف'}
{'id': 33384, 'title': '163798365214UTvhnxPB'}
{'id': 6538, 'title': '1591079650GZKUiXwpp5'}
{'id': 46284, 'title': '1651014560jUEtq3GU3W'}
{'id': 23896, 'title': 'مكررة'}
{'id': 21315, 'title': '1625130604y4QveF2U5e'}
{'id': 21316, 'title': '1625130604y4QveF2U5e'}
{'id': 21349, 'title': '1625130604y4QveF2U5e'}
{'id': 23943, 'title': 'طبيعة جديد'}
{'id': 30038, 'title': '1634218024o6Rqdk48tT'}
{'id': 17719, 'title': 'حذف'}
{'id': 17720, 'title': 'حذف'}
{'id': 31476, 'title': 'حذف'}
{'id': 2816, 'title': 'حذف'}
{'id': 16411, 'title': 'غير فعال'}
{'id': 16412, 'title': 'غير فعال'}
{'id': 17630, 'title': 'غير فعال'}
{'id': 17644, 'title': 'غير فعال'}
{'id': 17646, 'title': 'غير فعال'}
{'id': 33283, 'title': 'صحيح مقبول'}
{'id': 34853, 'title': 'unactive'}
{'id': 35320, 'title': 'unactive'}
{'id': 35319, 'title': 'تيست ديف مبرمج'}
{'id': 17006, 'title': 'للحذف'}
{'id': 17140, 'title': 'للحذف'}
{'id': 19866, 'title': 'للحذف'}
{'id': 19907, 'title': 'للحذف'}
{'id': 23526, 'title': 'للحذف'}
{'id': 18173, 'title': 'nice image'}
{'id': 25695, 'title': 'البحر '}
{'id': 37466, 'title': 'الوان تيست '}
{'id': 2357, 'title': 'eee'}
{'id': 2358, 'title': 'eee'}
{'id': 2359, 'title': 'eee'}
{'id': 44295, 'title': 'هل علينا موسم الحج'}
{'id': 35651, 'title': 'فطيرة البيتزا الشهيه الطازجه, بيتزا بالخضار والبيبروني, قطعه شهيه من فطيرة البيتزا, وجبات سريعه'}
{'id': 23957, 'title': 'اعلام المملكة العربية السعودية ترفرف في سماء السعودية ، الاحتفال باليوم الوطني السعودي ، العيد الوطني السعودي'}
{'id': 23959, 'title': 'اعلام المملكة العربية السعودية ترفرف في سماء السعودية ، الاحتفال باليوم الوطني السعودي ، العيد الوطني السعودي'}
{'id': 47815, 'title': 'سيدة عربية خليجية سعودية تحتفل بعيد ميلاد طفلتيها تقوم بإلتقاط صورة سيلفي تذكارية بإيماءات وجه و يدين تدل على السعادة ، الإحتفال بعيد الميلاد بأجواء عائلية ممتعة ، أعياد و مناسبات ، المفاجأة بهدايا عيد الميلاد ، مناسبات عائلية سعيدة'}
{'id': 47242, 'title': 'صورة لورقة نقدية من فئة 100 بيسة عليها صورة السلطان قابوس بن سعيد بن تيمور آل سعيد وسط الحقل، التمويل والاستثمار، الطبيعة، مؤسسة البنك المركزي العماني، العملة الرسمية لسلطنة عمان.'}
{'id': 47243, 'title': 'صورة لورقة نقدية من فئة 100 بيسة عليها صورة السلطان قابوس بن سعيد بن تيمور آل سعيد وسط الحقل، التمويل والاستثمار، الطبيعة، مؤسسة البنك المركزي العماني، العملة الرسمية لسلطنة عمان.'}
{'id': 47244, 'title': 'صورة لورقة نقدية من فئة 100 بيسة عليها صورة السلطان قابوس بن سعيد بن تيمور آل سعيد وسط الحقل، التمويل والاستثمار، الطبيعة، مؤسسة البنك المركزي العماني، العملة الرسمية لسلطنة عمان.'}
{'id': 47245, 'title': 'صورة لورقة نقدية من فئة 100 بيسة عليها صورة السلطان قابوس بن سعيد بن تيمور آل سعيد وسط الحقل، التمويل والاستثمار، الطبيعة، مؤسسة البنك المركزي العماني، العملة الرسمية لسلطنة عمان.'}
{'id': 47246, 'title': 'صورة لورقة نقدية من فئة 100 بيسة عليها صورة السلطان قابوس بن سعيد بن تيمور آل سعيد وسط الحقل، التمويل والاستثمار، الطبيعة، مؤسسة البنك المركزي العماني، العملة الرسمية لسلطنة عمان.'}
{'id': 32939, 'title': 'House'}
{'id': 26985, 'title': 'عرض جوي في احتفالات السعودية بذكرى اليوم الوطني ، عرض الطائرات لليوم الوطني السعودي ، الإحتفال بذكرى اليوم الوطني السعودي ، الطائرات السعودية تحلق في سماء المملكة العربية السعودية ، العيد الوطني للمملكة'}
{'id': 26986, 'title': 'عرض جوي في احتفالات السعودية بذكرى اليوم الوطني ، عرض الطائرات لليوم الوطني السعودي ، الإحتفال بذكرى اليوم الوطني السعودي ، الطائرات السعودية تحلق في سماء المملكة العربية السعودية ، العيد الوطني للمملكة'}
{'id': 26987, 'title': 'عرض جوي في احتفالات السعودية بذكرى اليوم الوطني ، عرض الطائرات لليوم الوطني السعودي ، الإحتفال بذكرى اليوم الوطني السعودي ، الطائرات السعودية تحلق في سماء المملكة العربية السعودية ، العيد الوطني للمملكة'}
{'id': 26988, 'title': 'عرض جوي في احتفالات السعودية بذكرى اليوم الوطني ، عرض الطائرات لليوم الوطني السعودي ، الإحتفال بذكرى اليوم الوطني السعودي ، الطائرات السعودية تحلق في سماء المملكة العربية السعودية ، العيد الوطني للمملكة'}
{'id': 26989, 'title': 'عرض جوي في احتفالات السعودية بذكرى اليوم الوطني ، عرض الطائرات لليوم الوطني السعودي ، الإحتفال بذكرى اليوم الوطني السعودي ، الطائرات السعودية تحلق في سماء المملكة العربية السعودية ، العيد الوطني للمملكة'}
{'id': 26990, 'title': 'عرض جوي في احتفالات السعودية بذكرى اليوم الوطني ، عرض الطائرات لليوم الوطني السعودي ، الإحتفال بذكرى اليوم الوطني السعودي ، الطائرات السعودية تحلق في سماء المملكة العربية السعودية ، العيد الوطني للمملكة'}
{'id': 26991, 'title': 'عرض جوي في احتفالات السعودية بذكرى اليوم الوطني ، عرض الطائرات لليوم الوطني السعودي ، الإحتفال بذكرى اليوم الوطني السعودي ، الطائرات السعودية تحلق في سماء المملكة العربية السعودية ، العيد الوطني للمملكة'}
{'id': 26992, 'title': 'عرض جوي في احتفالات السعودية بذكرى اليوم الوطني ، عرض الطائرات لليوم الوطني السعودي ، الإحتفال بذكرى اليوم الوطني السعودي ، الطائرات السعودية تحلق في سماء المملكة العربية السعودية ، العيد الوطني للمملكة'}
{'id': 26993, 'title': 'عرض جوي في احتفالات السعودية بذكرى اليوم الوطني ، عرض الطائرات لليوم الوطني السعودي ، الإحتفال بذكرى اليوم الوطني السعودي ، الطائرات السعودية تحلق في سماء المملكة العربية السعودية ، العيد الوطني للمملكة'}
{'id': 26994, 'title': 'عرض جوي في احتفالات السعودية بذكرى اليوم الوطني ، عرض الطائرات لليوم الوطني السعودي ، الإحتفال بذكرى اليوم الوطني السعودي ، الطائرات السعودية تحلق في سماء المملكة العربية السعودية ، العيد الوطني للمملكة'}
{'id': 26995, 'title': 'عرض جوي في احتفالات السعودية بذكرى اليوم الوطني ، عرض الطائرات لليوم الوطني السعودي ، الإحتفال بذكرى اليوم الوطني السعودي ، الطائرات السعودية تحلق في سماء المملكة العربية السعودية ، العيد الوطني للمملكة'}
{'id': 13833, 'title': 'بورتريه لشاب خليجي عربي يشير إلى الهاتف الخلوي بدهشة , خلفية سوداء '}
{'id': 13835, 'title': 'بورتريه لشاب خليجي عربي يشير إلى الهاتف الخلوي بدهشة , خلفية سوداء '}
{'id': 13837, 'title': 'بورتريه لشاب خليجي عربي يشير إلى الهاتف الخلوي بدهشة , خلفية سوداء '}
{'id': 36511, 'title': 'فطيرة البيتزا الشهيه الطازجه, بيتزا بالخضار , قطعه شهيه من فطيرة البيتزا, وجبات سريعه'}
{'id': 36512, 'title': 'فطيرة البيتزا الشهيه الطازجه, بيتزا بالخضار , قطعه شهيه من فطيرة البيتزا, وجبات سريعه'}
{'id': 36514, 'title': 'فطيرة البيتزا الشهيه الطازجه, بيتزا بالخضار , قطعه شهيه من فطيرة البيتزا, وجبات سريعه'}
{'id': 36515, 'title': 'فطيرة البيتزا الشهيه الطازجه, بيتزا بالخضار , قطعه شهيه من فطيرة البيتزا, وجبات سريعه'}
{'id': 27237, 'title': 'العلم الوطني للمملكة العربية السعودية يرفرف في السماء في وضع النهار، راية التوحيد والاسلام، الاحتفال باليوم الوطني السعودي، الإحتفال بالعيد الوطني السعودي، ذكرى توحيد المملكة العربية السعودية، ذكرى اليوم الوطني السعودي'}
{'id': 27240, 'title': 'العلم الوطني للمملكة العربية السعودية يرفرف في السماء في وضع النهار، راية التوحيد والاسلام، الاحتفال باليوم الوطني السعودي، الإحتفال بالعيد الوطني السعودي، ذكرى توحيد المملكة العربية السعودية، ذكرى اليوم الوطني السعودي'}
{'id': 23478, 'title': ' صورة من الخلف لرجل عربي خليجي سعودي يقف أمام بوابة عبور من خلال تقنية الهولوجرام ، تحقيق الأهداف والانجازات ، استخدام تقنية الهولوجرام ثلاثية الأبعاد .'}
{'id': 6215, 'title': 'مهندس مقاولة سعودي خليجي في موقع البناء ، بيده خوذة الحماية ، بناء خطط استراتيجية مستقبلية ناجحة'}
{'id': 6220, 'title': 'مهندس مقاولة سعودي خليجي في موقع البناء ، بيده خوذة الحماية ، بناء خطط استراتيجية مستقبلية ناجحة'}
{'id': 6221, 'title': 'مهندس مقاولة سعودي خليجي في موقع البناء ، بيده خوذة الحماية ، بناء خطط استراتيجية مستقبلية ناجحة'}
{'id': 6223, 'title': 'مهندس مقاولة سعودي خليجي في موقع البناء ، بيده خوذة الحماية ، بناء خطط استراتيجية مستقبلية ناجحة'}
{'id': 5040, 'title': 'محاسبة عربية خليجية سعودية تسلم كيس التسوق لعميل عربي خليجي سعودي ،  بائعة سعودية في محل لبيع الملابس ، الاستمتاع بالشراء والتسوق ، الاستفادة من العروض والخصومات ، قضاء وقت ممتع في التسوق من المول تجاري'}
{'id': 5041, 'title': 'محاسبة عربية خليجية سعودية تسلم كيس التسوق لعميل عربي خليجي سعودي ،  بائعة سعودية في محل لبيع الملابس ، الاستمتاع بالشراء والتسوق ، الاستفادة من العروض والخصومات ، قضاء وقت ممتع في التسوق من المول تجاري'}
{'id': 5042, 'title': 'محاسبة عربية خليجية سعودية تسلم كيس التسوق لعميل عربي خليجي سعودي ،  بائعة سعودية في محل لبيع الملابس ، الاستمتاع بالشراء والتسوق ، الاستفادة من العروض والخصومات ، قضاء وقت ممتع في التسوق من المول تجاري'}
{'id': 14626, 'title': 'بورتريه رجل سعودي خليجي يحمل صندوق هدية بين يديه  ، شراء الهدايا ،  الترفيه و التسوق ، خلفية ملونة'}
{'id': 14628, 'title': 'بورتريه رجل سعودي خليجي يحمل صندوق هدية بين يديه  ، شراء الهدايا ،  الترفيه و التسوق ، خلفية ملونة'}
{'id': 38840, 'title': 'صورة مقربة للصخور  بالمملكة العربية السعودية ، الطبيعة في السعودية ، خلفية الطبيعة ، أحجار ملونة ، صخور متلونة بالطحالب البحرية '}
{'id': 40574, 'title': 'انطلاق المهرجان البحري الرابع، بقاعدة الملك فيصل البحرية بجدة، تنظمه القوات البحرية الملكية السعودية في قيادة الأسطول الغربي، الطيران الشراعي، رجل سائح يقوم بتقديم عروض وفعاليات الطيران الشراعي، أنشطة وفعاليات في السعودية '}
{'id': 42800, 'title': 'صورة إبداعية لجبل الحوارة في محافظة العلا بالمملكة العربية السعودية ، أماكن سياحية بالسعودية ، معالم تاريخية وأثرية قديمة في بلدة العلا القديمة ، المناطق الصحراوية في محافظة العلا ، المرتفعات الجبلية والتكوينات الصخرية الطبيعية بالعلا'}
{'id': 42897, 'title': 'صورة إبداعية لجبل الحوارة في محافظة العلا بالمملكة العربية السعودية ، أماكن سياحية بالسعودية ، معالم تاريخية وأثرية قديمة في بلدة العلا القديمة ، المناطق الصحراوية في محافظة العلا ، المرتفعات الجبلية والتكوينات الصخرية الطبيعية بالعلا'}
{'id': 42898, 'title': 'صورة إبداعية لجبل الحوارة في محافظة العلا بالمملكة العربية السعودية ، أماكن سياحية بالسعودية ، معالم تاريخية وأثرية قديمة في بلدة العلا القديمة ، المناطق الصحراوية في محافظة العلا ، المرتفعات الجبلية والتكوينات الصخرية الطبيعية بالعلا'}
{'id': 42899, 'title': 'صورة إبداعية لجبل الحوارة في محافظة العلا بالمملكة العربية السعودية ، أماكن سياحية بالسعودية ، معالم تاريخية وأثرية قديمة في بلدة العلا القديمة ، المناطق الصحراوية في محافظة العلا ، المرتفعات الجبلية والتكوينات الصخرية الطبيعية بالعلا'}
{'id': 42900, 'title': 'صورة إبداعية لجبل الحوارة في محافظة العلا بالمملكة العربية السعودية ، أماكن سياحية بالسعودية ، معالم تاريخية وأثرية قديمة في بلدة العلا القديمة ، المناطق الصحراوية في محافظة العلا ، المرتفعات الجبلية والتكوينات الصخرية الطبيعية بالعلا'}
{'id': 42901, 'title': 'صورة إبداعية لجبل الحوارة في محافظة العلا بالمملكة العربية السعودية ، أماكن سياحية بالسعودية ، معالم تاريخية وأثرية قديمة في بلدة العلا القديمة ، المناطق الصحراوية في محافظة العلا ، المرتفعات الجبلية والتكوينات الصخرية الطبيعية بالعلا'}
{'id': 27242, 'title': 'صورة مقربة لمجموعة من بروشات العلم الوطني للمملكة العربية السعودية، راية التوحيد والاسلام، الاحتفال باليوم الوطني السعودي، ذكرى توحيد المملكة العربية السعودية، ذكرى اليوم الوطني السعودي، بروش سعودي، حب الوطن، شعار السعودية، العيد الوطني السعودي'}
{'id': 33061, 'title': 'منظر الجبال الشاهقة من الأعلى في مدينة الباحة بالمملكة العربية السعودية , الطبيعة الخلابة , السياحة والسفر .'}
{'id': 33062, 'title': 'منظر الجبال الشاهقة من الأعلى في مدينة الباحة بالمملكة العربية السعودية , الطبيعة الخلابة , السياحة والسفر .'}
{'id': 33063, 'title': 'منظر الجبال الشاهقة من الأعلى في مدينة الباحة بالمملكة العربية السعودية , الطبيعة الخلابة , السياحة والسفر .'}
{'id': 37077, 'title': 'سيدة عربية خليجية سعودية تقف امام خلفية لعلم المملكة العربية السعودية ، القاء كلمة ترحيبية في مؤتمر سعودي ، الاحتفال باليوم الوطني السعودي ، رجل سعودي خليجي يدون الملاحظات ، تقييم الموهوبين السعوديين ،  مؤتمرات و ندوات في السعودية'}
{'id': 37080, 'title': 'سيدة عربية خليجية سعودية تقف امام خلفية لعلم المملكة العربية السعودية ، القاء كلمة ترحيبية في مؤتمر سعودي ، الاحتفال باليوم الوطني السعودي ، رجل سعودي خليجي يدون الملاحظات ، تقييم الموهوبين السعوديين ،  مؤتمرات و ندوات في السعودية'}
{'id': 37082, 'title': 'سيدة عربية خليجية سعودية تقف امام خلفية لعلم المملكة العربية السعودية ، القاء كلمة ترحيبية في مؤتمر سعودي ، الاحتفال باليوم الوطني السعودي ، رجل سعودي خليجي يدون الملاحظات ، تقييم الموهوبين السعوديين ،  مؤتمرات و ندوات في السعودية'}
{'id': 36137, 'title': 'صورة لطبق خزفي ملون ومزخرف بالزخارف العربية الملونة , طبق ملون ومنقوش بنقشات جميلة '}
{'id': 36138, 'title': 'صورة لطبق خزفي ملون ومزخرف بالزخارف العربية الملونة , طبق ملون ومنقوش بنقشات جميلة '}
{'id': 40824, 'title': 'صورة مقربة لفتاة عربية خليجية ترتدي عباية معاصرة في مدينة دبي بالإمارات العربية المتحدة، جدران سيتي ووك بجميرا، أشهر المناطق السياحية الجديدة في الإمارات، لوحات فنية تجذب الزوار والسياح، رسومات ابداعية، السياحة في الامارات'}
{'id': 40825, 'title': 'صورة مقربة لفتاة عربية خليجية ترتدي عباية معاصرة في مدينة دبي بالإمارات العربية المتحدة، جدران سيتي ووك بجميرا، أشهر المناطق السياحية الجديدة في الإمارات، لوحات فنية تجذب الزوار والسياح، رسومات ابداعية، السياحة في الامارات'}
{'id': 44713, 'title': 'صورة مقربة لفتاة عربية خليجية ترتدي عباية معاصرة في مدينة دبي بالإمارات العربية المتحدة، جدران سيتي ووك بجميرا، أشهر المناطق السياحية الجديدة في الإمارات، لوحات فنية تجذب الزوار والسياح، رسومات ابداعية، السياحة في الامارات'}
{'id': 23624, 'title': 'بورتريه لرجل سعودي خليجي رافع يده ينظر بتركيز لشيء ما بإيماءات وجه ويدين مختلفة ، خلفية بيضاء لرجل سعودي مسلم يرتدي زي تقليدي سعودي مع شماغ وعقال'}
{'id': 28008, 'title': 'صورة لنقود سعودية، العملة الورقية السعودية، خلفية بيضاء، الريال السعودي من فئة العشرة، عشرة ريال'}
{'id': 21126, 'title': 'صورة جمالية خلابة لغروب وشروق الشمس , غروب وشروق الشمس الإبداعي من الصحراء, جمال الطبيعة الصحراوية الخلابة في وقت غروب وشروق الشمس منظر رائع وخلاب في سماء السعودية'}
{'id': 21127, 'title': 'صورة جمالية خلابة لغروب وشروق الشمس , غروب وشروق الشمس الإبداعي من الصحراء, جمال الطبيعة الصحراوية الخلابة في وقت غروب وشروق الشمس منظر رائع وخلاب في سماء السعودية'}
{'id': 21128, 'title': 'صورة جمالية خلابة لغروب وشروق الشمس , غروب وشروق الشمس الإبداعي من الصحراء, جمال الطبيعة الصحراوية الخلابة في وقت غروب وشروق الشمس منظر رائع وخلاب في سماء السعودية'}
{'id': 21129, 'title': 'صورة جمالية خلابة لغروب وشروق الشمس , غروب وشروق الشمس الإبداعي من الصحراء, جمال الطبيعة الصحراوية الخلابة في وقت غروب وشروق الشمس منظر رائع وخلاب في سماء السعودية'}
{'id': 21130, 'title': 'صورة جمالية خلابة لغروب وشروق الشمس , غروب وشروق الشمس الإبداعي من الصحراء, جمال الطبيعة الصحراوية الخلابة في وقت غروب وشروق الشمس منظر رائع وخلاب في سماء السعودية'}
{'id': 21131, 'title': 'صورة جمالية خلابة لغروب وشروق الشمس , غروب وشروق الشمس الإبداعي من الصحراء, جمال الطبيعة الصحراوية الخلابة في وقت غروب وشروق الشمس منظر رائع وخلاب في سماء السعودية'}
{'id': 21132, 'title': 'صورة جمالية خلابة لغروب وشروق الشمس , غروب وشروق الشمس الإبداعي من الصحراء, جمال الطبيعة الصحراوية الخلابة في وقت غروب وشروق الشمس منظر رائع وخلاب في سماء السعودية'}
{'id': 22401, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22402, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22414, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22416, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22417, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22419, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22421, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22422, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22423, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22425, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22426, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22428, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22431, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22432, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22433, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22434, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22436, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 22438, 'title': 'صوره لفاكهة الخوخ اللذيذ مصورة على خلفية سوداء ، فاكهة الدّراق الصحية اللذيذة ، فاكهة صيفية'}
{'id': 25721, 'title': 'صورة مقربة لرجل اعمال عربي سعودي خليجي ، يتحدث بالهاتف المحمول في داخل مقر الشركة ، يرتدي الزي السعودي التقليدي ، شركة سعودية ، وظيفة مكتبية ، بيئة عمل ، مكالمة صوتية على الهاتف الخلوي'}
{'id': 25724, 'title': 'صورة مقربة لرجل اعمال عربي سعودي خليجي ، يتحدث بالهاتف المحمول في داخل مقر الشركة ، يرتدي الزي السعودي التقليدي ، شركة سعودية ، وظيفة مكتبية ، بيئة عمل ، مكالمة صوتية على الهاتف الخلوي'}
{'id': 39038, 'title': 'صورة جمالية لمعرض الزهور في الأحساء بالمملكة العربية السعودية ، تشكيل أكبر صورة بالزهور لخادم الحرمين الشريفين الملك سلمان في كرنفال الزهور بمليون زهرة بالأحساء ، لوحة فنيه من الزهور والورود لخادم الحرمين الشريفين الملك سلمان بن عبدالعزيز آل سعود'}
{'id': 39039, 'title': 'صورة جمالية لمعرض الزهور في الأحساء بالمملكة العربية السعودية ، تشكيل أكبر صورة بالزهور لخادم الحرمين الشريفين الملك سلمان في كرنفال الزهور بمليون زهرة بالأحساء ، لوحة فنيه من الزهور والورود لخادم الحرمين الشريفين الملك سلمان بن عبدالعزيز آل سعود'}
{'id': 41736, 'title': 'صورة جمالية لمعرض الزهور في الأحساء بالمملكة العربية السعودية ، تشكيل أكبر صورة بالزهور لخادم الحرمين الشريفين الملك سلمان في كرنفال الزهور بمليون زهرة بالأحساء ، لوحة فنيه من الزهور والورود لخادم الحرمين الشريفين الملك سلمان بن عبدالعزيز آل سعود'}
{'id': 41738, 'title': 'صورة جمالية لمعرض الزهور في الأحساء بالمملكة العربية السعودية ، تشكيل أكبر صورة بالزهور لخادم الحرمين الشريفين الملك سلمان في كرنفال الزهور بمليون زهرة بالأحساء ، لوحة فنيه من الزهور والورود لخادم الحرمين الشريفين الملك سلمان بن عبدالعزيز آل سعود'}
{'id': 39676, 'title': 'صورة ظلية لاشجار النخيل بالمملكة العربية السعودية، اشعة الشمس المغطاة من قبل الاشجار، الطبيعة الخلابة في السعودية اثناء غروب الشمس'}
{'id': 39677, 'title': 'صورة ظلية لاشجار النخيل بالمملكة العربية السعودية، اشعة الشمس المغطاة من قبل الاشجار، الطبيعة الخلابة في السعودية اثناء غروب الشمس'}
{'id': 23322, 'title': 'شاب عربي خليجي سعودي ، يحمل بيده علم السعودية من فوق جبال الحشر في محافظة الداير في منطقة جازان بالمملكة العربية السعودية في وضع النهار ، اليوم الوطني السعودي ، السياحة بالسعودية، المناظر الطبيعية الأثرية الخلابة'}
{'id': 23324, 'title': 'شاب عربي خليجي سعودي ، يحمل بيده علم السعودية من فوق جبال الحشر في محافظة الداير في منطقة جازان بالمملكة العربية السعودية في وضع النهار ، اليوم الوطني السعودي ، السياحة بالسعودية، المناظر الطبيعية الأثرية الخلابة'}
{'id': 23325, 'title': 'شاب عربي خليجي سعودي ، يحمل بيده علم السعودية من فوق جبال الحشر في محافظة الداير في منطقة جازان بالمملكة العربية السعودية في وضع النهار ، اليوم الوطني السعودي ، السياحة بالسعودية، المناظر الطبيعية الأثرية الخلابة'}
{'id': 23326, 'title': 'شاب عربي خليجي سعودي ، يحمل بيده علم السعودية من فوق جبال الحشر في محافظة الداير في منطقة جازان بالمملكة العربية السعودية في وضع النهار ، اليوم الوطني السعودي ، السياحة بالسعودية، المناظر الطبيعية الأثرية الخلابة'}
{'id': 45584, 'title': 'صورة لعصفور الدوري ، عصفور الشجر ، طيور مغردة ،  الحياة البرية والطبيعة '}
{'id': 45585, 'title': 'صورة لعصفور الدوري ، عصفور الشجر ، طيور مغردة ،  الحياة البرية والطبيعة '}