In [1]:
try:
    import elasticsearch
    from elasticsearch import Elasticsearch
    
    import pandas as pd
    import json
    from ast import literal_eval
    from tqdm import tqdm
    import datetime
    import os
    import sys
    
    import os
    import tensorflow as tf
    import tensorflow_hub as hub
    import numpy as np
    
    from elasticsearch import helpers
    print("Loaded  .. . . . . . . .")
except Exception as E:
    print("Some Modules are Missing {} ".format(E))

2022-05-26 09:04:17.720549: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-26 09:04:17.720629: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

Loaded  .. . . . . . . .

In [3]:
try:
 print("Loaded  s .. . . . . . . .")
 module_url = "/home/forsan/Downloads/universal-sentence-encoder_4" 
 model = hub.load(module_url)    
 print ("module %s loaded" % module_url)
except Exception as E:
    print("Some Modules are Missing {} ".format(E))

Loaded  s .. . . . . . . .

2022-05-26 09:05:07.557736: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-05-26 09:05:07.557807: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-05-26 09:05:07.557861: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (devibrahim-forsan): /proc/driver/nvidia/version does not exist
2022-05-26 09:05:07.559336: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-26 09:05:08.827333: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 34133760 exceeds 10% of free system memory.
2022-05-26 09:05:09.015568: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 34133760 exceeds 10% of free system memory.
2022-05-26 09:05:09.201002: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 34133760 exceeds 10% of free system memory.
2022-05-26 09:05:09.341902: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 34133760 exceeds 10% of free system memory.
2022-05-26 09:05:09.533212: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 34133760 exceeds 10% of free system memory.

module /home/forsan/Downloads/universal-sentence-encoder_4 loaded

In [5]:
df = pd.read_csv("/home/forsan/Downloads/images (3).csv")

In [29]:
df.head(1)

  title    id
0   eee  2357

In [4]:
def apply_transform(x):
    
    tem = str(x)
    x = tf.constant([tem])
    embeddings = model(x)
    x = np.asarray(embeddings)
    x = x[0].tolist()
    return x

In [7]:
df["ml_vector"] = df["title"].apply(apply_transform)

In [8]:
len(df["ml_vector"].iloc[0])

512

In [10]:
df.head(1)

,id,title,ml_vector
0,26901,اجتماع زملاء عمل عربيون سعوديون خليجيون في...,"[-0.0581899955868721, 0.004004060756415129, 0...."

In [42]:
Settings = {
   "settings":{
      "number_of_shards":1,
      "number_of_replicas":0,
        "analysis": {
      "filter": {
        "arabic_stop": {
          "type":       "stop",
          "stopwords":  "_arabic_" 
        },
        "arabic_keywords": {
          "type":       "keyword_marker",
          "keywords":   ["مثال"] 
        },
        "arabic_stemmer": {
          "type":       "stemmer",
          "language":   "arabic"
        }
      },
      "analyzer": {
        "rebuilt_arabic": {
          "tokenizer":  "standard",
          "filter": [
            "lowercase",
            "decimal_digit",
            "arabic_stop",
            "arabic_normalization",
            "arabic_keywords",
            "arabic_stemmer"
          ]
        }
      }
    }
   },
   "mappings":{
       "properties":{
          "ml_vector":{
         "type":"dense_vector",
         "dims":512
      } 
    }
   }
}

In [5]:
ENDPOINT = "http://localhost:9200/"
es = Elasticsearch(timeout=600,hosts=ENDPOINT)

In [6]:
es.ping()

True

In [44]:
IndexName = 'arabstockimgdevv9'
my = es.indices.create(index=IndexName, ignore=[400,404], body=Settings)

In [45]:
my

{'acknowledged': True,
 'shards_acknowledged': True,
 'index': 'arabstockimgdevv9'}

In [46]:
df.columns

Index(['title', 'id', 'ml_vector'], dtype='object')

In [52]:
def generator(df2):
    for c, line in enumerate(df2):
        yield {
    '_index': 'arabstockimgdevv9',
   # '_type': '_doc',
    '_id': c+1,
    '_source': {
        "title":line.get("title", ""),
       'id':line.get('id', ""),
        'ml_vector':line.get('ml_vector', "")
    }
        }
    return 1

In [53]:
df22 = df.to_dict('records')
next(generator(df22))

{'_index': 'arabstockimgdevv9',
 '_id': 1,
 '_source': {'title': 'eee',
  'id': 2357,
  'ml_vector': [-0.054026804864406586,
   -0.03842293843626976,
   0.05653785169124603,
   0.06373250484466553,
   -0.019726933911442757,
   0.023887624964118004,
   0.0139841940253973,
   -0.07408511638641357,
   0.05501914024353027,
   -0.03269156813621521,
   -0.0397510901093483,
   0.04740298539400101,
   -0.020027706399559975,
   -0.044217370450496674,
   -0.07171943038702011,
   0.013836477883160114,
   0.015241413377225399,
   0.051613256335258484,
   0.05137060955166817,
   -0.02418549358844757,
   0.07176473736763,
   -0.022440357133746147,
   0.04952561855316162,
   -0.05686269327998161,
   -0.05336103215813637,
   0.05125395581126213,
   0.013357373885810375,
   -0.03176634758710861,
   -0.03422686085104942,
   -0.0017391917062923312,
   0.006891636177897453,
   -0.04215896874666214,
   -0.03958765044808388,
   -0.06786327809095383,
   0.0647006705403328,
   -0.06879260390996933,
   0.017542773857712746,
   0.08008121699094772,
   -0.018433859571814537,
   0.07960997521877289,
   0.04008840397000313,
   0.021168110892176628,
   -0.02916675992310047,
   -0.018548499792814255,
   0.03313477709889412,
   0.07439318299293518,
   0.03841232508420944,
   -0.02452743798494339,
   -0.04223654419183731,
   -0.06752186268568039,
   -0.07239193469285965,
   0.00249694986268878,
   0.07717753201723099,
   0.08789671957492828,
   0.035171572118997574,
   0.039613813161849976,
   -0.060122519731521606,
   0.026996329426765442,
   -0.0046868715435266495,
   0.04847615212202072,
   0.0020807767286896706,
   -0.013545614667236805,
   -7.072742300806567e-05,
   -0.057219211012125015,
   0.0760435089468956,
   0.029097696766257286,
   -0.022955479100346565,
   -0.0560121089220047,
   0.017127886414527893,
   0.06395307928323746,
   -0.036279890686273575,
   -0.02791077084839344,
   -0.07202531397342682,
   -0.0033359848894178867,
   -0.01646076887845993,
   -0.027999108657240868,
   0.0260879248380661,
   -0.05383412912487984,
   0.050576504319906235,
   -0.0381922610104084,
   -0.07073591649532318,
   -0.002861237619072199,
   -0.02905222214758396,
   0.017174558714032173,
   -0.03634742274880409,
   -0.007298251613974571,
   -0.0198933444917202,
   0.0557512529194355,
   0.0647185668349266,
   -0.0046313791535794735,
   -0.04602079838514328,
   0.044991444796323776,
   -0.008591994643211365,
   -0.07891335338354111,
   0.017995361238718033,
   0.05151590332388878,
   -0.026736397296190262,
   -0.07541270554065704,
   0.01241181418299675,
   -0.026898983865976334,
   0.010438666678965092,
   -0.058454081416130066,
   0.039075855165719986,
   0.04537675529718399,
   -0.005325804930180311,
   0.0038964087143540382,
   0.03783688321709633,
   0.012037855572998524,
   0.010348564945161343,
   -0.004822195507586002,
   0.021121278405189514,
   0.05233967304229736,
   -0.00463867699727416,
   0.030790038406848907,
   -0.027452312409877777,
   0.0369381420314312,
   -0.07707931846380234,
   -0.027518300339579582,
   0.031100580468773842,
   0.0404314324259758,
   -0.03085866943001747,
   -0.0029934276826679707,
   0.03720377758145332,
   -0.03265223652124405,
   0.08159813284873962,
   -0.048550475388765335,
   0.032996825873851776,
   -0.045631296932697296,
   0.022399259731173515,
   0.04953137785196304,
   -0.05257581174373627,
   0.044086799025535583,
   0.07759027928113937,
   0.07253585010766983,
   -0.021471448242664337,
   0.047906242311000824,
   0.03293408080935478,
   -0.041423168033361435,
   -0.007774025667458773,
   -0.016880767419934273,
   -0.07266627997159958,
   0.06119257211685181,
   0.02212901972234249,
   -0.034699175506830215,
   0.02980554848909378,
   0.0427468940615654,
   -0.013036785647273064,
   -0.05372917652130127,
   -0.02050808258354664,
   -0.018166767433285713,
   -0.011292205192148685,
   0.043359480798244476,
   -0.04097240790724754,
   0.07114560157060623,
   0.023359868675470352,
   -0.04104186221957207,
   -0.07401487231254578,
   0.0641595795750618,
   -0.033707063645124435,
   0.03185073658823967,
   0.043855104595422745,
   0.038897864520549774,
   -0.047384925186634064,
   -0.0762220174074173,
   0.015762021765112877,
   -0.01763232983648777,
   -0.031099533662199974,
   -0.0024090714287012815,
   0.07171296328306198,
   0.013086609542369843,
   -0.0623655803501606,
   0.05480651929974556,
   -0.01694446988403797,
   -0.07148145139217377,
   -0.05449686944484711,
   -0.009837326593697071,
   0.012869438156485558,
   -0.033938564360141754,
   -0.05725403130054474,
   0.0010998060461133718,
   0.006051083095371723,
   -0.027101967483758926,
   -0.06765950471162796,
   0.05018173158168793,
   0.026910806074738503,
   0.02893874980509281,
   -0.023664815351366997,
   -0.024287616834044456,
   0.07301468402147293,
   0.03614719957113266,
   0.020431824028491974,
   -0.03630508854985237,
   -0.024893397465348244,
   -0.06365212798118591,
   0.016207540407776833,
   -0.05902741476893425,
   -0.03086807020008564,
   -0.031746458262205124,
   0.026782091706991196,
   0.03348023444414139,
   -0.08509109914302826,
   -0.012302697636187077,
   -0.06298337131738663,
   0.01994611695408821,
   -0.05386481061577797,
   -0.017049124464392662,
   -0.04336509108543396,
   0.006296973675489426,
   0.05712878331542015,
   -0.056800056248903275,
   0.023886574432253838,
   0.019046567380428314,
   -0.00815212819725275,
   0.043593864887952805,
   0.05125082656741142,
   0.028711538761854172,
   -0.0647699311375618,
   -0.0670304223895073,
   -0.039194513112306595,
   -0.00928530003875494,
   -0.0029774836730211973,
   0.05289964750409126,
   -4.4070406147511676e-05,
   -0.05722362920641899,
   0.024745609611272812,
   0.009629249572753906,
   -0.035687968134880066,
   -0.06032102182507515,
   -0.05101833492517471,
   0.00027408264577388763,
   -0.00798797607421875,
   -0.04204854741692543,
   0.005006041843444109,
   0.09280896186828613,
   -0.0634448304772377,
   0.039449889212846756,
   -0.012303613126277924,
   -0.010347790084779263,
   -0.06113828718662262,
   -0.02869090624153614,
   0.001756561454385519,
   0.030870066955685616,
   -0.031295325607061386,
   -0.04490034282207489,
   0.07095840573310852,
   -0.05497462674975395,
   0.05314713716506958,
   -0.06489522010087967,
   -0.05480562150478363,
   -0.016987387090921402,
   0.00029391745920293033,
   0.07885490357875824,
   0.038509584963321686,
   -0.00291848205961287,
   0.06294776499271393,
   -0.07508143037557602,
   0.005699506960809231,
   0.07145220786333084,
   -0.025401055812835693,
   0.04322182759642601,
   -0.01482111494988203,
   -0.007531450595706701,
   -0.07315760850906372,
   -0.07662494480609894,
   0.06718848645687103,
   -0.06813047081232071,
   0.07151634246110916,
   -0.04537639021873474,
   -0.023167502135038376,
   -0.07043861597776413,
   -0.007854358293116093,
   0.05878143012523651,
   -0.019117292016744614,
   -0.030532918870449066,
   0.08183784037828445,
   0.008987991139292717,
   -0.022143661975860596,
   0.04468868300318718,
   0.06950012594461441,
   -0.07702118903398514,
   0.004017560742795467,
   0.001683128415606916,
   0.026018600910902023,
   0.056594789028167725,
   -0.033128462731838226,
   -0.03245789557695389,
   0.05076673999428749,
   -0.05111585557460785,
   -0.03634817153215408,
   -0.07027581334114075,
   0.01927630789577961,
   -0.06587786972522736,
   0.024584902450442314,
   0.009670248255133629,
   0.0319359116256237,
   0.016394995152950287,
   -0.06957772374153137,
   -0.06615837663412094,
   0.02533261477947235,
   0.04564288631081581,
   -0.04202454164624214,
   -0.008671539835631847,
   -0.058302849531173706,
   0.061289988458156586,
   -0.014807903207838535,
   0.05831708759069443,
   -0.00441606855019927,
   0.011534699238836765,
   -0.01562974601984024,
   -0.04851726070046425,
   -0.032442573457956314,
   -0.05483778193593025,
   -0.054869845509529114,
   0.00543850427493453,
   -0.008797825314104557,
   0.027362190186977386,
   0.022154197096824646,
   -0.08170939236879349,
   -0.05253468453884125,
   -0.0264821108430624,
   0.05490337312221527,
   -0.0446716733276844,
   -0.046390678733587265,
   0.0007723502931185067,
   0.012842472642660141,
   0.030434006825089455,
   -0.03959183022379875,
   0.047332193702459335,
   0.00878096278756857,
   -0.01702781207859516,
   0.003279147669672966,
   0.03289509192109108,
   -0.08092931658029556,
   0.08517318218946457,
   -0.05719686672091484,
   0.015502522699534893,
   0.038600463420152664,
   0.04839671030640602,
   -0.0522783137857914,
   -0.004124182742089033,
   -0.04680626839399338,
   0.02660609968006611,
   -0.009275970049202442,
   0.025171635672450066,
   -0.06425944715738297,
   0.030174674466252327,
   -0.052521612495183945,
   -0.04598260298371315,
   -0.020024960860610008,
   0.0030139293521642685,
   -0.030382083728909492,
   0.0647590383887291,
   0.0186269860714674,
   0.015919407829642296,
   -0.004515585955232382,
   -0.05003504827618599,
   -0.07487504929304123,
   -0.06678944826126099,
   0.044498808681964874,
   -0.03819818049669266,
   0.013419657945632935,
   -0.04745473712682724,
   0.08173839002847672,
   -0.009946937672793865,
   -0.0012816464295610785,
   -0.025147028267383575,
   0.025439638644456863,
   0.02134418860077858,
   0.002670725341886282,
   -0.03415411338210106,
   0.05064677819609642,
   -0.06497879326343536,
   0.055173590779304504,
   -0.03189297392964363,
   -0.07142139226198196,
   -0.038774099200963974,
   0.00826418586075306,
   -0.07121051847934723,
   0.053957514464855194,
   -0.08189989626407623,
   0.05661539360880852,
   0.02348477952182293,
   0.00877548661082983,
   -0.0863959789276123,
   0.02291034162044525,
   -0.0743182972073555,
   0.048674605786800385,
   0.07384605705738068,
   0.009323532693088055,
   -0.0024044145829975605,
   -0.03377895802259445,
   0.0807652696967125,
   0.03184789419174194,
   -0.0648421123623848,
   0.01899362914264202,
   -0.05387967452406883,
   0.06660978496074677,
   0.07601357251405716,
   -0.04257117584347725,
   0.03989449888467789,
   -0.007103349082171917,
   0.0846031904220581,
   -0.002690668450668454,
   -0.04039234295487404,
   0.024026157334446907,
   0.06163632124662399,
   0.005294770933687687,
   0.028352322056889534,
   0.04850449785590172,
   0.018773535266518593,
   -0.03563912212848663,
   0.019524209201335907,
   -0.00324318278580904,
   -0.006166640669107437,
   -0.04039410874247551,
   -0.016155531629920006,
   0.08515487611293793,
   -0.022918477654457092,
   -0.04006616026163101,
   0.018347255885601044,
   0.038913216441869736,
   -0.08571115881204605,
   -0.07610020786523819,
   0.049202874302864075,
   -0.0367656871676445,
   0.00997812021523714,
   -0.023148201406002045,
   0.06914713978767395,
   -0.02119734324514866,
   0.002380089834332466,
   -0.06416164338588715,
   -0.032258033752441406,
   -0.0663779228925705,
   -0.0054730759002268314,
   0.04704497009515762,
   0.018103376030921936,
   0.017061127349734306,
   0.023823987692594528,
   -0.03469330072402954,
   0.09124425053596497,
   -0.028894705697894096,
   -0.03178009018301964,
   0.03751637786626816,
   0.014502482488751411,
   -0.012555086053907871,
   -0.03580435737967491,
   -0.028960492461919785,
   -0.01184273324906826,
   0.03236617520451546,
   -0.0056631979532539845,
   -0.013330665417015553,
   0.0014721155166625977,
   -0.004504592157900333,
   0.023846538737416267,
   0.01062270812690258,
   -0.0632147267460823,
   0.023128865286707878,
   -0.05493997409939766,
   0.06008950620889664,
   -0.05310953035950661,
   0.033158473670482635,
   0.04780306667089462,
   -0.03088604472577572,
   0.015473872423171997,
   0.02529398910701275,
   0.04042034596204758,
   0.02644786424934864,
   0.02676970511674881,
   0.03773660585284233,
   0.013239598833024502,
   0.04115109518170357,
   -0.019614320248365402,
   0.06704370677471161,
   0.027535468339920044,
   0.06943093240261078,
   0.01315488200634718,
   -0.03593273460865021,
   -0.001558505347929895,
   0.03207311034202576,
   0.05499354377388954,
   -0.04634809121489525,
   -0.07598365843296051,
   0.022489087656140327,
   0.044371746480464935,
   0.022701499983668327,
   0.03054976649582386,
   -0.04657731205224991,
   0.057284995913505554,
   0.028862271457910538,
   -0.05218137055635452,
   -0.005445985589176416,
   0.04078710451722145,
   -0.034451600164175034,
   -0.0414041168987751,
   -0.006355587858706713,
   -0.029329048469662666,
   0.06967300176620483,
   -0.008471831679344177,
   0.06362753361463547,
   0.02366829290986061,
   0.023035723716020584,
   0.008498583920300007,
   -0.03185214847326279,
   -0.08955687284469604,
   0.05944940820336342,
   0.05914272367954254,
   -0.01708265393972397,
   -0.07670924812555313,
   0.05971861630678177,
   -0.051417719572782516,
   0.007355287671089172,
   -0.07041109353303909]}}

In [54]:
try:
    print("start working")
    res = helpers.bulk(es, generator(df22))
    print("end Working")
except Exception as E:
    print("Some Modules are Missing {} ".format(E))

start working
end Working

In [8]:
title = "Krish Trish and Baltiboy: Best Friends Forever"
INPUT = input("Enter input query")

x = apply_transform(INPUT)
Query = {
   "_source":[
      "title","id"
   ],
   "size":3000,
   "query":{
      "script_score":{
         "query":{
           # "match":{"title":INPUT}
             "match_all": {}
         },
         "script":{
            "source":"cosineSimilarity(params.query_vector, 'ml_vector') + 1.0",
       #  "source": """
        #  double value = dotProduct(params.query_vector, 'ml_vector');
         # return sigmoid(1, Math.E, -value); 
        #""",
                     #"source": "1 / (1 + l1norm(params.query_vector, 'ml_vector'))", 

            "params":{
               "query_vector":x

            }
         }
      }
   }
}


resp = es.search(index="arabstockimgdevv9",  body=Query)

print("Got %d Hits:" % resp['hits']['total']['value'])
#print(resp)
for hit in resp['hits']['hits']:
    print(  hit["_source"])

Enter input query صورة خلفية مقربة لباب من حديد قديم بارز الشكل

Got 10000 Hits:
{'id': 24590, 'title': 'صورة خلفية مقربة لباب من حديد قديم بارز الشكل'}
{'id': 26285, 'title': 'صورة لسيارات الأجرة بانتظار المسافرين عند مخرج مطار دبي الدولي بالإمارات العربية المتحدة، المواصلات والسياحة في الإمارات'}
{'id': 26286, 'title': 'صورة لسيارات الأجرة بانتظار المسافرين عند مخرج مطار دبي الدولي بالإمارات العربية المتحدة، المواصلات والسياحة في الإمارات'}
{'id': 24756, 'title': 'صورة مقربة للحاء الشجرة الخشبي ، الطبيعة في السعودية ، جذع الشجرة ، خلفية الخشب البني  '}
{'id': 39896, 'title': 'صورة لطبق من اللحم المشوي ، وجبات طعام ، وجبات لحوم ، مطعم شواء ، مطاعم عربية خليجية سعودية'}
{'id': 40441, 'title': 'صورة جمالية لورد صناعي في وعاء خشبي، ساعة رملية، ديكورات جميلة '}
{'id': 15232, 'title': 'صورة مقربة من الأعلى , لرجل خليجي سعودي يضع معلومات تذاكر الرحلات الى اللابتوب في المطار , بيئة عمل , خلفية بيضاء .'}
{'id': 15234, 'title': 'صورة مقربة من الأعلى , لرجل خليجي سعودي يضع معلومات تذاكر الرحلات الى اللابتوب في المطار , بيئة عمل , خلفية بيضاء .'}
{'id': 15236, 'title': 'صورة مقربة من الأعلى , لرجل خليجي سعودي يضع معلومات تذاكر الرحلات الى اللابتوب في المطار , بيئة عمل , خلفية بيضاء .'}
{'id': 15238, 'title': 'صورة مقربة من الأعلى , لرجل خليجي سعودي يضع معلومات تذاكر الرحلات الى اللابتوب في المطار , بيئة عمل , خلفية بيضاء .'}
{'id': 15239, 'title': 'صورة مقربة من الأعلى , لرجل خليجي سعودي يضع معلومات تذاكر الرحلات الى اللابتوب في المطار , بيئة عمل , خلفية بيضاء .'}
{'id': 17355, 'title': 'بورتريه شاب مراهق خليجي سعودي بإيماءات وجه يدين مختلفة تدل على النعس و الحاجة للنوم ، خلفية بيضاء'}
{'id': 40812, 'title': 'صورة من الخلف لفتاة عربية خليجية ترتدي عباية معاصرة، النظر لبرج العرب، معالم دبي المشهورة، سياحة وسفر، ابراج وناطحات سحاب، السياحة في الإمارات'}
{'id': 46907, 'title': 'صورة من الداخل لاحد المطاعم، طاولة مطعم ، جلسات هادئة، تصاميم وديكورات، ديكورات مميزة'}
{'id': 22805, 'title': 'صورة خلفية مقربة لباب حجري قديم بارز الشكل'}
{'id': 22806, 'title': 'صورة خلفية مقربة لباب حجري قديم بارز الشكل'}
{'id': 22807, 'title': 'صورة خلفية مقربة لباب حجري قديم بارز الشكل'}
{'id': 22808, 'title': 'صورة خلفية مقربة لباب حجري قديم بارز الشكل'}
{'id': 22809, 'title': 'صورة خلفية مقربة لباب حجري قديم بارز الشكل'}
{'id': 24589, 'title': 'صورة خلفية مقربة لباب حجري قديم بارز الشكل'}
{'id': 44508, 'title': 'صورة مقربة لطبق من التمر الصحي، وجبة ذات قيمة غذائية عالية، ضيافة رمضانية، انواع من التمور الصحية واللذيذة، خلفية سوداء'}
{'id': 44509, 'title': 'صورة مقربة لطبق من التمر الصحي، وجبة ذات قيمة غذائية عالية، ضيافة رمضانية، انواع من التمور الصحية واللذيذة، خلفية سوداء'}
{'id': 17306, 'title': 'بورتريه شاب مراهق خليجي سعودي بإيماءات وجه ويدين مختلفة تدل على الغضب ، خلفية بيضاء'}
{'id': 20922, 'title': ' صورة إبداعية ظلية لجمل (الإبل) من الحيوانات الصحراوية شديدة الصبر والتحمل تمشي في الصحراء بالسعودية , الجمل سفينة الصحراء , السياحة الصحراوية'}
{'id': 17228, 'title': 'بورتريه شاب مراهق خليجي سعودي بإيماءات وجه ويدين مختلفة تدل على البكاء و الحزن ، خلفية بيضاء'}
{'id': 17402, 'title': 'بورتريه شاب مراهق خليجي سعودي بإيماءات وجه ويدين مختلفة تدل على البكاء و الحزن ، خلفية بيضاء'}
{'id': 17405, 'title': 'بورتريه شاب مراهق خليجي سعودي بإيماءات وجه ويدين مختلفة تدل على البكاء و الحزن ، خلفية بيضاء'}
{'id': 17352, 'title': 'بورتريه شاب مراهق خليجي سعودي بإيماءات وجه ويدين مختلفة تدل على التفكير و التركيز ، خلفية بيضاء'}
{'id': 17396, 'title': 'بورتريه شاب مراهق خليجي سعودي بإيماءات وجه ويدين مختلفة تدل على التفكير و التركيز ، خلفية بيضاء'}
{'id': 44493, 'title': 'صورة مقربة لأسوارة توضع على اليد مصورة على خلفية سوداء ، مجوهرات ، إكسسوارات ، فن التصوير الإحترافي'}
{'id': 29082, 'title': 'صورة مقربة لعلامة سيارة كلاسيكية من شركة مرسيدس مشاركة في احتفالات اليوم الوطني لدولة الإمارات العربية المتحدة، بوادي مول، فعاليات الإمارات.'}
{'id': 29084, 'title': 'صورة مقربة لعلامة سيارة كلاسيكية من شركة مرسيدس مشاركة في احتفالات اليوم الوطني لدولة الإمارات العربية المتحدة، بوادي مول، فعاليات الإمارات.'}
{'id': 44510, 'title': 'صورة مقربة لطبق من التمر الصحي، وجبة ذات قيمة غذائية عالية، ضيافة رمضانية، انواع من التمور الصحية واللذيذة'}
{'id': 44514, 'title': 'صورة مقربة لطبق من التمر الصحي، وجبة ذات قيمة غذائية عالية، ضيافة رمضانية، انواع من التمور الصحية واللذيذة'}
{'id': 16629, 'title': 'صورة مقربة لفاكهة التوت الحلو الطازج على خلفية طاولة خشبية '}
{'id': 16630, 'title': 'صورة مقربة لفاكهة التوت الحلو الطازج على خلفية طاولة خشبية '}
{'id': 16631, 'title': 'صورة مقربة لفاكهة التوت الحلو الطازج على خلفية طاولة خشبية '}
{'id': 25854, 'title': 'صورة مقربة لحلويات الدونات المتنوعة في علبة ورقية ، حلوى الدونات الشهية واللذيذة ، حلويات هشه طازجة'}
{'id': 39405, 'title': 'صورة لطبق من الماكولات المقلية ، الكبة الذهبية والسمبوسة الشهية ، اصناف من المأكولات الشرقية ،  مطاعم عربية '}
{'id': 39406, 'title': 'صورة لطبق من الماكولات المقلية ، الكبة الذهبية والسمبوسة الشهية ، اصناف من المأكولات الشرقية ،  مطاعم عربية '}
{'id': 39407, 'title': 'صورة لطبق من الماكولات المقلية ، الكبة الذهبية والسمبوسة الشهية ، اصناف من المأكولات الشرقية ،  مطاعم عربية '}
{'id': 39639, 'title': 'صورة لطبق من الماكولات المقلية ، الكبة الذهبية والسمبوسة الشهية ، اصناف من المأكولات الشرقية ،  مطاعم عربية '}
{'id': 45579, 'title': 'صورة مقربة من أعلى لأيدي مجموعة أشخاص يتناولون وجبة الفطور ، وجبات عربية ، وصفات وأطباق طعام لذيذة ، مأكولات صحية'}
{'id': 32197, 'title': 'بورتريه لشاب عربي خليجي سعودي، إيماءات وجه ويدين تدل على السعادة والحماس، شاب اسمر، خلفية بيضاء'}
{'id': 32198, 'title': 'بورتريه لشاب عربي خليجي سعودي، إيماءات وجه ويدين تدل على السعادة والحماس، شاب اسمر، خلفية بيضاء'}
{'id': 3496, 'title': 'بورتريه لفتاة عربية خليجية سعودية مكتفة يديها بإيماءات تدل على الغضب ، خلفية بيضاء'}
{'id': 36140, 'title': 'صورة لقطع من البسكويت المقرمش متناثر على خلفية بيضاء , قطع البسكويت المحشوة بقطع الشوكولاتة  . '}
{'id': 36301, 'title': 'صورة لقطع من البسكويت المقرمش متناثر على خلفية بيضاء , قطع البسكويت المحشوة بقطع الشوكولاتة  . '}
{'id': 42034, 'title': 'صورة لاطباق واصناف من التمر الصحي ، وجبة ذات قيمة غذائية عالية  ، ضيافة رمضانية ،انواع من التمور الصحية واللذيذة '}
{'id': 42035, 'title': 'صورة لاطباق واصناف من التمر الصحي ، وجبة ذات قيمة غذائية عالية  ، ضيافة رمضانية ،انواع من التمور الصحية واللذيذة '}
{'id': 44260, 'title': 'صورة لطائرة من طيران الإمارات تحلق فوق مطار دبي الدولي، وسائل المواصلات الجوية ،رحلات جوية سياحية ، السياحة في الإمارات العربية المتحدة'}
{'id': 44261, 'title': 'صورة لطائرة من طيران الإمارات تحلق فوق مطار دبي الدولي، وسائل المواصلات الجوية ،رحلات جوية سياحية ، السياحة في الإمارات العربية المتحدة'}
{'id': 44285, 'title': 'صورة لطائرة من طيران الإمارات تحلق فوق مطار دبي الدولي، وسائل المواصلات الجوية ،رحلات جوية سياحية ، السياحة في الإمارات العربية المتحدة'}
{'id': 44288, 'title': 'صورة لطائرة من طيران الإمارات تحلق فوق مطار دبي الدولي، وسائل المواصلات الجوية ،رحلات جوية سياحية ، السياحة في الإمارات العربية المتحدة'}
{'id': 41008, 'title': 'صورة مقربة لتمثال مخترع عربي داخل ابن بطوطة مول بدبي بالإمارات العربية المتحدة، السياحة في الإمارات.'}
{'id': 15928, 'title': 'بورتريه لطبق من التمر الفاخر اللذيذ ، شهر رمضان ، رمضان كريم ، خلفية بيضاء'}
{'id': 15136, 'title': 'صورة مقربة من الأعلى , لبيئة عمل مخصصة للتجميل , مهن ووظيفة , خلفيه بيضاء .  '}
{'id': 44387, 'title': 'صورة مقربة لفندق كراون بلازا في مدينة دبي بالإمارات العربية المتحدة، الفن الهندسي المعماري المميز، معالم دبي، السياحة في الإمارات'}
{'id': 41824, 'title': 'صورة مقربة لنخلة عديمة الساق، خلفية للطبيعة، اشجار ونباتات، زراعة الأشجار في السعودية'}
{'id': 17394, 'title': 'بورتريه شاب مراهق خليجي سعودي يضع يده على ظهره يشعر بحالة من الوجع والألم بإيماءات وجه ويدين مختلفة  , خلفية بيضاء'}
{'id': 27661, 'title': 'صورة للوحة إعلانية ضخمة لطيران الإمارات خارج مطار دبي الدولي بالإمارات العربية المتحدة، ترويج وإعلانات، شركات الطيران، السياحة في الإمارات.'}
{'id': 27662, 'title': 'صورة للوحة إعلانية ضخمة لطيران الإمارات خارج مطار دبي الدولي بالإمارات العربية المتحدة، ترويج وإعلانات، شركات الطيران، السياحة في الإمارات.'}
{'id': 27663, 'title': 'صورة للوحة إعلانية ضخمة لطيران الإمارات خارج مطار دبي الدولي بالإمارات العربية المتحدة، ترويج وإعلانات، شركات الطيران، السياحة في الإمارات'}
{'id': 17250, 'title': 'بورتريه شاب مراهق خليجي سعودي يضع يده على رقبته يشعر بحالة من الوجع والألم بإيماءات وجه ويدين مختلفة , خلفية بيضاء'}
{'id': 17253, 'title': 'بورتريه شاب مراهق خليجي سعودي يضع يده على رقبته يشعر بحالة من الوجع والألم بإيماءات وجه ويدين مختلفة , خلفية بيضاء'}
{'id': 17376, 'title': 'بورتريه شاب مراهق خليجي سعودي يضع يده على رقبته يشعر بحالة من الوجع والألم بإيماءات وجه ويدين مختلفة , خلفية بيضاء'}
{'id': 17381, 'title': 'بورتريه شاب مراهق خليجي سعودي يضع يده على رقبته يشعر بحالة من الوجع والألم بإيماءات وجه ويدين مختلفة , خلفية بيضاء'}
{'id': 19873, 'title': 'صورة مقربة لرجل عربي خليجي سعودي أمام خلفية تحتوي على مجموعة من الطائرات الورقية المتطايرة بإيماءات وجه ويدين تدل عالتفكير و الحيرة .'}
{'id': 41703, 'title': 'صورة من أعلى لرجال أمن ، الحرص على سلامة الناس ، توفير الأمن والأمان ، الحراسة ، القيام بمهام ودوريات يومية ، الإمارات العربية المتحدة'}
{'id': 3178, 'title': 'صورة مقربة لاجتماع فريق عمل من رجل و سيدة اعمال سعوديين خليجيين ، العمل على الكمبيوتر المحمول ، بيئة العمل ، شركة سعودية'}
{'id': 29076, 'title': 'صورة مقربة لعلامة سيارة كلاسيكية من شركة فورد مشاركة في احتفالات اليوم الوطني لدولة الإمارات العربية المتحدة، بوادي مول، فعاليات الإمارات.'}
{'id': 29079, 'title': 'صورة مقربة لعلامة سيارة كلاسيكية من شركة فورد مشاركة في احتفالات اليوم الوطني لدولة الإمارات العربية المتحدة، بوادي مول، فعاليات الإمارات.'}
{'id': 29080, 'title': 'صورة مقربة لعلامة سيارة كلاسيكية من شركة فورد مشاركة في احتفالات اليوم الوطني لدولة الإمارات العربية المتحدة، بوادي مول، فعاليات الإمارات.'}
{'id': 44511, 'title': 'صورة مقربة لطبق من التمر الصحي، تمر دقلة نور، وجبة ذات قيمة غذائية عالية، ضيافة رمضانية، انواع من التمور الصحية واللذيذة'}
{'id': 44512, 'title': 'صورة مقربة لطبق من التمر الصحي، تمر دقلة نور، وجبة ذات قيمة غذائية عالية، ضيافة رمضانية، انواع من التمور الصحية واللذيذة'}
{'id': 44513, 'title': 'صورة مقربة لطبق من التمر الصحي، تمر دقلة نور، وجبة ذات قيمة غذائية عالية، ضيافة رمضانية، انواع من التمور الصحية واللذيذة'}
{'id': 19926, 'title': 'صورة مقربة لرجل ريادي أعمال عربي خليجي سعودي أمام خلفية تحتوي على مجموعة من الطائرات الورقية المتطايرة بإيماءات وجه ويدين تدل عالتفكير و تطوير الأفكار ، مهارة الابداع .'}
{'id': 21021, 'title': 'صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية سوداء'}
{'id': 21271, 'title': 'صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية سوداء'}
{'id': 14438, 'title': 'أب خليجي يقضي وقتا ممتعا مع ابنته , قضاء أجمل الأوقات مع العائلة , خروج عائلة سعودية من الفندق للإستمتاع , سياحة وسفر .'}
{'id': 14439, 'title': 'أب خليجي يقضي وقتا ممتعا مع ابنته , قضاء أجمل الأوقات مع العائلة , خروج عائلة سعودية من الفندق للإستمتاع , سياحة وسفر .'}
{'id': 14442, 'title': 'أب خليجي يقضي وقتا ممتعا مع ابنته , قضاء أجمل الأوقات مع العائلة , خروج عائلة سعودية من الفندق للإستمتاع , سياحة وسفر .'}
{'id': 14444, 'title': 'أب خليجي يقضي وقتا ممتعا مع ابنته , قضاء أجمل الأوقات مع العائلة , خروج عائلة سعودية من الفندق للإستمتاع , سياحة وسفر .'}
{'id': 14449, 'title': 'أب خليجي يقضي وقتا ممتعا مع ابنته , قضاء أجمل الأوقات مع العائلة , خروج عائلة سعودية من الفندق للإستمتاع , سياحة وسفر .'}
{'id': 13287, 'title': 'مرأه عربية خليجية سعيدة في احدى المتاجر ،تعمل على الكمبيوتر المحمول ، بجانبها  فنجان القهوة ،  متجر القهوه ، بيئة العمل'}
{'id': 13289, 'title': 'مرأه عربية خليجية سعيدة في احدى المتاجر ،تعمل على الكمبيوتر المحمول ، بجانبها  فنجان القهوة ،  متجر القهوه ، بيئة العمل'}
{'id': 13292, 'title': 'مرأه عربية خليجية سعيدة في احدى المتاجر ،تعمل على الكمبيوتر المحمول ، بجانبها  فنجان القهوة ،  متجر القهوه ، بيئة العمل'}
{'id': 13293, 'title': 'مرأه عربية خليجية سعيدة في احدى المتاجر ،تعمل على الكمبيوتر المحمول ، بجانبها  فنجان القهوة ،  متجر القهوه ، بيئة العمل'}
{'id': 13294, 'title': 'مرأه عربية خليجية سعيدة في احدى المتاجر ،تعمل على الكمبيوتر المحمول ، بجانبها  فنجان القهوة ،  متجر القهوه ، بيئة العمل'}
{'id': 13295, 'title': 'مرأه عربية خليجية سعيدة في احدى المتاجر ،تعمل على الكمبيوتر المحمول ، بجانبها  فنجان القهوة ،  متجر القهوه ، بيئة العمل'}
{'id': 13300, 'title': 'مرأه عربية خليجية سعيدة في احدى المتاجر ،تعمل على الكمبيوتر المحمول ، بجانبها  فنجان القهوة ،  متجر القهوه ، بيئة العمل'}
{'id': 28031, 'title': 'صورة من الخلف لرجل عربي خليجي سعودي يرتدي الزي السعودي التقليدي ، يقف مستقيماً و يديه جانباً ، خلفية رمادية'}
{'id': 42410, 'title': 'أطباق من التمر الصحي، وجبة ذات قيمة غذائية عالية، ضيافة رمضانية، انواع من التمور الصحية واللذيذة، خلفية بيضاء'}
{'id': 42411, 'title': 'أطباق من التمر الصحي، وجبة ذات قيمة غذائية عالية، ضيافة رمضانية، انواع من التمور الصحية واللذيذة، خلفية بيضاء'}
{'id': 42412, 'title': 'أطباق من التمر الصحي، وجبة ذات قيمة غذائية عالية، ضيافة رمضانية، انواع من التمور الصحية واللذيذة، خلفية بيضاء'}
{'id': 38907, 'title': 'صورة مقربة لفنجان قهوة اسبريسو بيد رجل ، نسكافيه ، مشروب القهوة الساخن ، خلفية سوداء'}
{'id': 43468, 'title': 'صورة مقربة لحبة الطماطم الحمراء على خلفية صفراء'}
{'id': 41504, 'title': 'صورة من خلف السياج لبرج خليفة في دبي بالامارات العربية المتحدة، الفن الهندسي المعماري بالإمارات، معالم الإمارات المشهورة، ابراج وناطحات سحاب، السياحة في الإمارات'}
{'id': 41528, 'title': 'صورة من خلف السياج لبرج خليفة في دبي بالامارات العربية المتحدة، الفن الهندسي المعماري بالإمارات، معالم الإمارات المشهورة، ابراج وناطحات سحاب، السياحة في الإمارات'}
{'id': 21038, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21039, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21041, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21042, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21043, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21045, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21046, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21048, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21050, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21052, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21053, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21054, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21090, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21091, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21093, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء '}
{'id': 21094, 'title': 'مجموعة من نباتات القمح ، صورة مقربة لشرائح خبز التوست المحمصة مصورة على خلفية بيضاء'}
{'id': 40139, 'title': 'صورة من الخلف لشاب عربي خليجي سعودي، الاستعداد للإمساك بطائرة بدون طيار، طائرة درون، غروب الشمس، طائرة تصوير جوي'}
{'id': 42541, 'title': 'صورة مقربة لسعف النخلة، خلفية للطبيعة، اشجار ونباتات، زراعة الأشجار في السعودية'}
{'id': 17285, 'title': 'بورتريه شاب مراهق خليجي سعودي مريض يضع يده على رأسه بإيماءات وجه ويدين مختلفة تدل على الألم و الوجع ، خلفية بيضاء'}
{'id': 17296, 'title': 'بورتريه شاب مراهق خليجي سعودي مريض يضع يده على رأسه بإيماءات وجه ويدين مختلفة تدل على الألم و الوجع ، خلفية بيضاء'}
{'id': 17297, 'title': 'بورتريه شاب مراهق خليجي سعودي مريض يضع يده على رأسه بإيماءات وجه ويدين مختلفة تدل على الألم و الوجع ، خلفية بيضاء'}
{'id': 17299, 'title': 'بورتريه شاب مراهق خليجي سعودي مريض يضع يده على رأسه بإيماءات وجه ويدين مختلفة تدل على الألم و الوجع ، خلفية بيضاء'}
{'id': 17300, 'title': 'بورتريه شاب مراهق خليجي سعودي مريض يضع يده على رأسه بإيماءات وجه ويدين مختلفة تدل على الألم و الوجع ، خلفية بيضاء'}
{'id': 17311, 'title': 'بورتريه شاب مراهق خليجي سعودي مريض يضع يده على رأسه بإيماءات وجه ويدين مختلفة تدل على الألم و الوجع ، خلفية بيضاء'}
{'id': 17356, 'title': 'بورتريه شاب مراهق خليجي سعودي مريض يضع يده على رأسه بإيماءات وجه ويدين مختلفة تدل على الألم و الوجع ، خلفية بيضاء'}
{'id': 17357, 'title': 'بورتريه شاب مراهق خليجي سعودي مريض يضع يده على رأسه بإيماءات وجه ويدين مختلفة تدل على الألم و الوجع ، خلفية بيضاء'}
{'id': 17359, 'title': 'بورتريه شاب مراهق خليجي سعودي مريض يضع يده على رأسه بإيماءات وجه ويدين مختلفة تدل على الألم و الوجع ، خلفية بيضاء'}
{'id': 33700, 'title': 'صورة لطبق مكون من كبسة الدجاج السعودية الشعبية , طبق النشويات والبروتين المغذي للجسم .'}
{'id': 33701, 'title': 'صورة لطبق مكون من كبسة الدجاج السعودية الشعبية , طبق النشويات والبروتين المغذي للجسم .'}
{'id': 17350, 'title': 'بورتريه شاب مراهق خليجي سعودي يشير بإصبعه بحالة من الغضب بإيماءات وجه ويدين مختلفة , خلفية بيضاء'}
{'id': 40751, 'title': 'صورة مقربة لطائر الحمام يطير فوق الأشجار، الأشجار والنباتات، خلفية للطبيعة، مجموعة من طيور الحمام'}
{'id': 30921, 'title': 'صورة مقربة ليد رجل عربي خليجي سعودي يستخدم الهاتف المحمول ، ايماءة اليد تدل على حجب الرؤيا والمشاهدة ، خلفية صفراء'}
{'id': 3494, 'title': 'بورتريه لفتاة عربية خليجية سعودية مكتفة يديها بإيماءات تدل على السعادة  ، خلفية بيضاء'}
{'id': 3495, 'title': 'بورتريه لفتاة عربية خليجية سعودية مكتفة يديها بإيماءات تدل على السعادة  ، خلفية بيضاء'}
{'id': 3497, 'title': 'بورتريه لفتاة عربية خليجية سعودية مكتفة يديها بإيماءات تدل على السعادة  ، خلفية بيضاء'}
{'id': 3498, 'title': 'بورتريه لفتاة عربية خليجية سعودية مكتفة يديها بإيماءات تدل على السعادة  ، خلفية بيضاء'}
{'id': 40810, 'title': 'صورة جانبية لفتاة عربية خليجية ترتدي عباية معاصرة، النظر لبرج العرب، معالم دبي المشهورة، سياحة وسفر، ابراج وناطحات سحاب، السياحة في الإمارات'}
{'id': 40811, 'title': 'صورة جانبية لفتاة عربية خليجية ترتدي عباية معاصرة، النظر لبرج العرب، معالم دبي المشهورة، سياحة وسفر، ابراج وناطحات سحاب، السياحة في الإمارات'}
{'id': 25743, 'title': 'صورة لخلفية أوراق نقدية سعودية، العملة الورقية السعودية، خلفية، الريال السعودي من فئة خمسمائة'}
{'id': 27272, 'title': 'صورة مقربة لشاب سعودي خليجي يعمل من خلال جهاز التابليت المحمول، يضغط باصبعه على شاشة التابليت، استخدام تقنيات متطورة، تقنية وحاسب'}
{'id': 30338, 'title': 'سلاسل جبليه, طرق جبيله وعره, منظر طبيعي, جمال الطبيعه الخلابه في المملكه العربيه السعوديه, معالم طبيعيه'}
{'id': 30339, 'title': 'سلاسل جبليه, طرق جبيله وعره, منظر طبيعي, جمال الطبيعه الخلابه في المملكه العربيه السعوديه, معالم طبيعيه'}
{'id': 23304, 'title': 'صورة مقربة لحصان بني اللون في إسطبل بجدة ، حيوان ثديي أليف ، رعي الخيول'}
{'id': 23305, 'title': 'صورة مقربة لحصان بني اللون في إسطبل بجدة ، حيوان ثديي أليف ، رعي الخيول'}
{'id': 23306, 'title': 'صورة مقربة لحصان بني اللون في إسطبل بجدة ، حيوان ثديي أليف ، رعي الخيول'}
{'id': 23307, 'title': 'صورة مقربة لحصان بني اللون في إسطبل بجدة ، حيوان ثديي أليف ، رعي الخيول'}
{'id': 30112, 'title': 'بورتريه لفتى خليجي سعودي يعاني من الم في الاسنان والاضراس، ايماءات الوجه واليد تدل على الوجع والالام ،خلفية بيضاء'}
{'id': 30113, 'title': 'بورتريه لفتى خليجي سعودي يعاني من الم في الاسنان والاضراس، ايماءات الوجه واليد تدل على الوجع والالام ،خلفية بيضاء'}
{'id': 30114, 'title': 'بورتريه لفتى خليجي سعودي يعاني من الم في الاسنان والاضراس، ايماءات الوجه واليد تدل على الوجع والالام ،خلفية بيضاء'}
{'id': 30115, 'title': 'بورتريه لفتى خليجي سعودي يعاني من الم في الاسنان والاضراس، ايماءات الوجه واليد تدل على الوجع والالام ،خلفية بيضاء'}
{'id': 30120, 'title': 'بورتريه لفتى خليجي سعودي يعاني من الم في الاسنان والاضراس، ايماءات الوجه واليد تدل على الوجع والالام ،خلفية بيضاء'}
{'id': 25742, 'title': 'صورة لخلفية أوراق نقدية سعودية، العملة الورقية السعودية، خلفية، الريال السعودي من فئة المائة والخمسمائة'}
{'id': 7725, 'title': 'بورتريه لشابة عربية خليجية سعودية ترتدي الكمامة  وتقوم بوضع الكمامة لطفلها ، اتباع اجراءات السلامة والوقاية من فايروس كورونا ، تجنب انتشار العدوى ، خلفية بيضاء'}
{'id': 7729, 'title': 'بورتريه لشابة عربية خليجية سعودية ترتدي الكمامة  وتقوم بوضع الكمامة لطفلها ، اتباع اجراءات السلامة والوقاية من فايروس كورونا ، تجنب انتشار العدوى ، خلفية بيضاء'}